/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CARPC_H_RPCGEN
#define	_CARPC_H_RPCGEN

#include <rpc/rpc.h>

struct CA_BCNA {
	int b;
	int c;
	int n;
	int a;
};
typedef struct CA_BCNA CA_BCNA;

struct CA_FXD {
	int f;
	int ext;
	int dat;
};
typedef struct CA_FXD CA_FXD;

struct CA_DQ {
	int dat;
	int q;
};
typedef struct CA_DQ CA_DQ;

struct CA_XL {
	int ext;
	int l;
};
typedef struct CA_XL CA_XL;

struct CA_LL {
	int lam;
	int l;
};
typedef struct CA_LL CA_LL;

#define	CASRVR	0x2c0da009
#define	CAVERS	1
#define	CA_RPCCDREG	1
extern  int * ca_rpccdreg_1();
#define	CA_RPCCFSA	2
extern  CA_DQ * ca_rpccfsa_1();
#define	CA_RPCCCCZ	3
extern  int * ca_rpccccz_1();
#define	CA_RPCCCCC	4
extern  int * ca_rpccccc_1();
#define	CA_RPCCCCI	5
extern  int * ca_rpcccci_1();
#define	CA_RPCCTCI	6
extern  int * ca_rpcctci_1();
#define	CA_RPCCCCD	7
extern  int * ca_rpccccd_1();
#define	CA_RPCCTCD	8
extern  int * ca_rpcctcd_1();
#define	CA_RPCCTGL	9
extern  int * ca_rpcctgl_1();
#define	CA_RPCCDLAM	10
extern  int * ca_rpccdlam_1();
#define	CA_RPCCCLM	11
extern  int * ca_rpccclm_1();
#define	CA_RPCCCLC	12
extern  int * ca_rpccclc_1();
#define	CA_RPCCTLM	13
extern  int * ca_rpcctlm_1();
#define	CA_RPCCCLWT	14
extern  int * ca_rpccclwt_1();
#define	CA_RPCCCINIT	15
extern  int * ca_rpcccinit_1();
#define	CA_RPCCTSTAT	16
extern  int * ca_rpcctstat_1();
#define	CA_RPCCTSTATUS	17
extern  int * ca_rpcctstatus_1();
extern int casrvr_1_freeresult();

/* the xdr functions */
extern bool_t xdr_CA_BCNA();
extern bool_t xdr_CA_FXD();
extern bool_t xdr_CA_DQ();
extern bool_t xdr_CA_XL();
extern bool_t xdr_CA_LL();

#endif /* !_CARPC_H_RPCGEN */
