//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HallBFlexTriggerGUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HALLBFLEXTRIGGERGUI_DIALOG  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_SECTOR_DIALOG               129
#define IDD_TRIGGER_DIALOG              130
#define IDD_SCOPE_DIALOG                132
#define IDD_TEST_DIALOG                 133
#define IDD_DEBUG_DIALOG                134
#define IDD_TRIGGER12_DIALOG            135
#define IDC_TAB_TRIGMAIN                1002
#define IDC_SP_MULTMAX                  1004
#define IDC_SP_PERSIST                  1005
#define IDC_B_SCOPE                     1006
#define IDC_SP_ST_DLY3                  1006
#define IDC_B_LOADSETTINGS              1007
#define IDC_SCROLL_SCOPE                1007
#define IDC_SP_ST_DLY4                  1007
#define IDC_B_CONNECT                   1008
#define IDC_SP_TOF_DLY                  1008
#define IDC_B_DISCONNECT                1009
#define IDC_SP_MULTMIN                  1009
#define IDC_SP_PRESCALE                 1010
#define IDC_B_FIRMWARE                  1010
#define IDC_SP_MORA_DLY                 1011
#define IDC_B_SAVESETTINGS              1012
#define IDC_SP_MORB_DLY                 1012
#define IDC_B_LOAD_STOF_ECP             1013
#define IDC_SP_CC_DLY                   1013
#define IDC_B_LOAD_STOF_ECC             1014
#define IDC_SP_E_CC_DLY                 1014
#define IDC_ST_LUT_SCALER               1015
#define IDC_ECP_LUT_SCALER              1015
#define IDC_ST_LUT_MOR_SCALER           1016
#define IDC_ST_LUT_MOR_ST_SCALER        1017
#define IDC_ST_STMULT_SCALER            1018
#define IDC_B_LOAD_TRIG                 1018
#define IDC_ST_PERSIST_SCALER           1019
#define IDC_B_LOAD_ECP                  1019
#define IDC_ST_PRESCALE_SCALER          1020
#define IDC_ST_TRIGGER_SCALER           1020
#define IDC_ST_TRIGOUT                  1021
#define IDC_ST_ST1                      1022
#define IDC_IC_TOT1_SCALER              1022
#define IDC_ST_ST2                      1023
#define IDC_IC_ELE1_SCALER              1023
#define IDC_ST_ST3                      1024
#define IDC_IC_VET1_SCALER              1024
#define IDC_ST_ST4                      1025
#define IDC_IC_TOT2_SCALER              1025
#define IDC_ST_TOF                      1026
#define IDC_IC_ELE2_SCALER              1026
#define IDC_ST_ECINP                    1027
#define IDC_IC_VET2_SCALER              1027
#define IDC_ST_ECTOTP                   1028
#define IDC_IC_TOT3_SCALER              1028
#define IDC_ST_ECINE                    1029
#define IDC_IC_ELE3_SCALER              1029
#define IDC_ST_ECTOTE                   1030
#define IDC_IC_VET3_SCALER              1030
#define IDC_ST_CC                       1031
#define IDC_B_LOAD_ECE                  1031
#define IDC_SP_ST_DLY1                  1032
#define IDC_ST_TOF2                     1032
#define IDC_B_LOAD_ECC                  1032
#define IDC_SP_ST_DLY2                  1033
#define IDC_ECE_LUT_SCALER              1033
#define IDC_ST_E_ECINE                  1033
#define IDC_SP_ECINP_DLY                1034
#define IDC_ECC_LUT_SCALER              1034
#define IDC_SP_ECTOTP_DLY               1035
#define IDC_SP_ECINE_DLY                1036
#define IDC_SP_ECTOTE_DLY               1037
#define IDC_ST_ST_DLY1                  1038
#define IDC_ST_E_ECTOTE                 1038
#define IDC_ST_ST_DLY2                  1039
#define IDC_ST_E_CC                     1039
#define IDC_ST_ST_DLY3                  1040
#define IDC_SP_E_ECINE_DLY              1040
#define IDC_ST_ST_DLY4                  1041
#define IDC_SP_E_ECTOTE_DLY             1041
#define IDC_ST_TOF_DLY                  1042
#define IDC_ST_ECINP_DLY                1043
#define IDC_ST_ECTOTP_DLY               1044
#define IDC_ST_ECINE_DLY                1045
#define IDC_ST_ECTOTE_DLY               1046
#define IDC_ST_CC_DLY                   1047
#define IDC_ST_ST_SCALER1               1048
#define IDC_ST_E_ECINE_DLY              1048
#define IDC_ST_ST_SCALER2               1049
#define IDC_ST_E_ECTOTE_DLY             1049
#define IDC_ST_ST_SCALER3               1050
#define IDC_ST_E_CC_DLY                 1050
#define IDC_ST_ST_SCALER4               1051
#define IDC_ST_TOF_SCALER               1052
#define IDC_ST_ECINP_SCALER             1053
#define IDC_ST_ECTOTP_SCALER            1054
#define IDC_ST_ECINE_SCALER             1055
#define IDC_ST_ECTOTE_SCALER            1056
#define IDC_ST_CC_SCALER                1057
#define IDC_ST_STS_SCALER               1058
#define IDC_ST_STOF_SCALER              1059
#define IDC_ST_ECP_SCALER               1060
#define IDC_ST_ECE_SCALER               1061
#define IDC_ST_ECC_SCALER               1062
#define IDC_ST_STOF_MODE                1063
#define IDC_ST_E_ECC_SCALER             1063
#define IDC_ST_ECC_MODE                 1064
#define IDC_ST_MOR_MODE                 1065
#define IDC_ST_PERSIST                  1066
#define IDC_ST_PRESCALE                 1067
#define IDC_ST_MULTMINMAX               1068
#define IDC_ST_MORA_DLY                 1069
#define IDC_ST_MORB_DLY                 1070
#define IDC_SL_SCALERPERIOD             1071
#define IDC_ST_SCALERPERIOD             1072
#define IDC_ST_STOF                     1073
#define IDC_ST_ECP                      1074
#define IDC_ST_ECC                      1075
#define IDC_ST_ECE                      1076
#define IDC_ST_STS                      1077
#define IDC_ST_E_ECC                    1077
#define IDC_LIST_DEBUG                  1078
#define IDC_ST_MORA_SCALER              1079
#define IDC_ST_MORB_SCALER              1080
#define IDC_ST_MOROR_SCALER             1081
#define IDC_ST_CURSORTIME               1081
#define IDC_CH_DEBUGENABLE              1082
#define IDC_ST_MOUSEPOS                 1083
#define IDC_ST_MOUSEPOS_SEC             1084
#define IDC_ST_ECPLUT_FILE              1085
#define IDC_ST_ECCLUT_FILE              1086
#define IDC_B_SCOPESTOP                 1086
#define IDC_B_SCOPESINGLE               1087
#define IDC_B_SCOPECONTINUOUS           1088
#define IDC_B_SCOPECLEAR                1090
#define IDC_CH_PERSIST                  1091
#define IDC_B_DBGCLEAR                  1092
#define IDC_EDIT_PATTERN                1095
#define IDC_B_PATTERN                   1096
#define IDC_ST_STMULT_MODE              1097
#define IDC_ST_STATIC                   1098
#define IDC_ST_STATIC2                  1099
#define IDC_ST_STATIC3                  1100
#define IDC_ST_STATIC4                  1101
#define IDC_ST_STATIC5                  1102
#define IDC_ST_STATIC6                  1103
#define IDC_ST_STATIC9                  1104
#define IDC_E_SERVERADDR                1105
#define IDC_B_PROG                      1106
#define IDC_B_START                     1107
#define IDC_B_STOP                      1108
#define IDC_ST_TESTSTATUS               1109
#define IDC_SP_IC_DLY                   1110
#define IDC_ST_IC_DLY                   1111

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
