c      include file EC1_PED
c
c  COMMON BLOCK NAME should be the same as include file name!
c
c  variables for include file EC1_PED
c  -----------------------------------
c  
c  Variables contained in EC1_PEDS common block
c  --------------------------------------------
c
c_end_var
c
       INTEGER ec1_pedupdt, ec1_pedl(40,4,2), ec1_pedr(40,4,2)
       COMMON/EC1_PEDS/ec1_pedupdt,ec1_pedl,ec1_pedr
c
c      ec1 pedestals
c----6----------------------------------------------------------------72























