#!/bin/sh
if [ $1 ]; then
  if [ `echo $1 | cut -b 1-1` = '-' ]; then
    # We do have CmdLine Parameters
    echo "seek $2" > tmp.vme
    vmecall tmp.vme $1
  else
    echo "seek $1" > tmp.vme
    vmecall tmp.vme
  fi	       
else
  echo "Usage: "
fi  
