/********************************************************************************
** Form generated from reading UI file 'motor_expert.ui'
**
** Created: Wed Oct 2 14:37:13 2013
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MOTOR_EXPERT_H
#define UI_MOTOR_EXPERT_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QWidget>
#include <cachoice.h>
#include <caframe.h>
#include <cagraphics.h>
#include <calabel.h>
#include <calineedit.h>
#include <camenu.h>
#include <camessagebutton.h>
#include <catextentry.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    caLabel *caLabel_0;
    caLabel *caLabel_1;
    caLabel *caLabel_2;
    caLabel *caLabel_3;
    caLabel *caLabel_4;
    caLabel *caLabel_5;
    caLabel *caLabel_6;
    caGraphics *caRectangle_0;
    caGraphics *caRectangle_1;
    caMessageButton *caMessageButton_0;
    caMessageButton *caMessageButton_1;
    caTextEntry *caTextEntry_0;
    caMessageButton *caMessageButton_2;
    caMessageButton *caMessageButton_3;
    caTextEntry *caTextEntry_1;
    caMessageButton *caMessageButton_4;
    caMessageButton *caMessageButton_5;
    caLabel *caLabel_7;
    caLabel *caLabel_8;
    caLabel *caLabel_9;
    caChoice *caChoice_0;
    caTextEntry *caTextEntry_2;
    caFrame *caFrame_0;
    caLabel *caLabel_10;
    caChoice *caChoice_1;
    caTextEntry *caTextEntry_3;
    caTextEntry *caTextEntry_4;
    caLabel *caLabel_11;
    caTextEntry *caTextEntry_5;
    caLabel *caLabel_12;
    caTextEntry *caTextEntry_6;
    caLabel *caLabel_13;
    caLabel *caLabel_14;
    caLabel *caLabel_15;
    caTextEntry *caTextEntry_7;
    caLabel *caLabel_16;
    caLabel *caLabel_17;
    caLabel *caLabel_18;
    caTextEntry *caTextEntry_8;
    caLabel *caLabel_19;
    caTextEntry *caTextEntry_9;
    caLabel *caLabel_20;
    caTextEntry *caTextEntry_10;
    caLabel *caLabel_21;
    caTextEntry *caTextEntry_11;
    caLabel *caLabel_22;
    caLineEdit *caLineEdit_0;
    caLabel *caLabel_23;
    caLabel *caLabel_24;
    caLineEdit *caLineEdit_1;
    caLabel *caLabel_25;
    caLineEdit *caLineEdit_2;
    caLineEdit *caLineEdit_3;
    caLabel *caLabel_26;
    caLabel *caLabel_27;
    caLabel *caLabel_28;
    caLabel *caLabel_29;
    caLabel *caLabel_30;
    caLineEdit *caLineEdit_4;
    caLabel *caLabel_31;
    caLineEdit *caLineEdit_5;
    caLineEdit *caLineEdit_6;
    caLineEdit *caLineEdit_7;
    caLineEdit *caLineEdit_8;
    caLabel *caLabel_32;
    caChoice *caChoice_2;
    caLabel *caLabel_33;
    caChoice *caChoice_3;
    caLabel *caLabel_34;
    caTextEntry *caTextEntry_12;
    caLabel *caLabel_35;
    caLabel *caLabel_36;
    caChoice *caChoice_4;
    caChoice *caChoice_5;
    caLabel *caLabel_37;
    caLabel *caLabel_38;
    caLabel *caLabel_39;
    caLabel *caLabel_40;
    caLabel *caLabel_41;
    caLabel *caLabel_42;
    caLineEdit *caLineEdit_9;
    caLineEdit *caLineEdit_10;
    caLineEdit *caLineEdit_11;
    caTextEntry *caTextEntry_13;
    caTextEntry *caTextEntry_14;
    caFrame *caFrame_1;
    caTextEntry *caTextEntry_15;
    caTextEntry *caTextEntry_16;
    caTextEntry *caTextEntry_17;
    caTextEntry *caTextEntry_18;
    caTextEntry *caTextEntry_19;
    caChoice *caChoice_6;
    caGraphics *caGraphics_0;
    caGraphics *caGraphics_1;
    caLabel *caLabel_43;
    caLabel *caLabel_44;
    caGraphics *caRectangle_2;
    caLabel *caLabel_45;
    caTextEntry *caTextEntry_20;
    caLabel *caLabel_46;
    caTextEntry *caTextEntry_21;
    caLineEdit *caLineEdit_12;
    caLabel *caLabel_47;
    caTextEntry *caTextEntry_22;
    caFrame *caFrame_2;
    caTextEntry *caTextEntry_23;
    caLabel *caLabel_48;
    caTextEntry *caTextEntry_24;
    caFrame *caFrame_3;
    caGraphics *caRectangle_3;
    caGraphics *caRectangle_4;
    caLabel *caLabel_49;
    caLineEdit *caLineEdit_13;
    caMenu *caMenu_0;
    caLineEdit *caLineEdit_14;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(438, 625);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        caLabel_0 = new caLabel(centralWidget);
        caLabel_0->setObjectName(QString::fromUtf8("caLabel_0"));
        caLabel_0->setFrameShape(QFrame::NoFrame);
        caLabel_0->setForeground(QColor(0, 0, 0, 255));
        caLabel_0->setBackground(QColor(0, 0, 0, 0));
        caLabel_0->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_0->setGeometry(QRect(155, 4, 180, 15));
        caLabel_0->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_1 = new caLabel(centralWidget);
        caLabel_1->setObjectName(QString::fromUtf8("caLabel_1"));
        caLabel_1->setFrameShape(QFrame::NoFrame);
        caLabel_1->setForeground(QColor(0, 0, 0, 255));
        caLabel_1->setBackground(QColor(0, 0, 0, 0));
        caLabel_1->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_1->setGeometry(QRect(3, 47, 86, 18));
        caLabel_1->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_2 = new caLabel(centralWidget);
        caLabel_2->setObjectName(QString::fromUtf8("caLabel_2"));
        caLabel_2->setFrameShape(QFrame::NoFrame);
        caLabel_2->setForeground(QColor(0, 0, 0, 255));
        caLabel_2->setBackground(QColor(0, 0, 0, 0));
        caLabel_2->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_2->setGeometry(QRect(1, 71, 86, 18));
        caLabel_2->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_3 = new caLabel(centralWidget);
        caLabel_3->setObjectName(QString::fromUtf8("caLabel_3"));
        caLabel_3->setFrameShape(QFrame::NoFrame);
        caLabel_3->setForeground(QColor(0, 0, 0, 255));
        caLabel_3->setBackground(QColor(0, 0, 0, 0));
        caLabel_3->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_3->setGeometry(QRect(1, 126, 86, 18));
        caLabel_3->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_4 = new caLabel(centralWidget);
        caLabel_4->setObjectName(QString::fromUtf8("caLabel_4"));
        caLabel_4->setFrameShape(QFrame::NoFrame);
        caLabel_4->setForeground(QColor(0, 0, 0, 255));
        caLabel_4->setBackground(QColor(0, 0, 0, 0));
        caLabel_4->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_4->setGeometry(QRect(2, 99, 75, 18));
        caLabel_4->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_5 = new caLabel(centralWidget);
        caLabel_5->setObjectName(QString::fromUtf8("caLabel_5"));
        caLabel_5->setFrameShape(QFrame::NoFrame);
        caLabel_5->setForeground(QColor(0, 0, 0, 255));
        caLabel_5->setBackground(QColor(0, 0, 0, 0));
        caLabel_5->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_5->setGeometry(QRect(0, 187, 57, 19));
        caLabel_5->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_6 = new caLabel(centralWidget);
        caLabel_6->setObjectName(QString::fromUtf8("caLabel_6"));
        caLabel_6->setFrameShape(QFrame::NoFrame);
        caLabel_6->setForeground(QColor(0, 0, 0, 255));
        caLabel_6->setBackground(QColor(0, 0, 0, 0));
        caLabel_6->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_6->setGeometry(QRect(-1, 161, 75, 18));
        caLabel_6->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caRectangle_0 = new caGraphics(centralWidget);
        caRectangle_0->setObjectName(QString::fromUtf8("caRectangle_0"));
        caRectangle_0->setForm(caGraphics::Rectangle);
        caRectangle_0->setGeometry(QRect(240, 183, 49, 24));
        caRectangle_0->setLineSize(2);
        caRectangle_0->setForeground(QColor(236, 236, 236, 255));
        caRectangle_0->setBackground(QColor(236, 236, 236, 0));
        caRectangle_0->setLineColor(QColor(236, 236, 236, 255));
        caRectangle_0->setLinestyle(caGraphics::Solid);
        caRectangle_0->setVisibility(caGraphics::IfNotZero);
        caRectangle_1 = new caGraphics(centralWidget);
        caRectangle_1->setObjectName(QString::fromUtf8("caRectangle_1"));
        caRectangle_1->setForm(caGraphics::Rectangle);
        caRectangle_1->setGeometry(QRect(189, 183, 49, 24));
        caRectangle_1->setLineSize(2);
        caRectangle_1->setForeground(QColor(236, 236, 236, 255));
        caRectangle_1->setBackground(QColor(236, 236, 236, 0));
        caRectangle_1->setLineColor(QColor(236, 236, 236, 255));
        caRectangle_1->setLinestyle(caGraphics::Solid);
        caRectangle_1->setVisibility(caGraphics::IfNotZero);
        caMessageButton_0 = new caMessageButton(centralWidget);
        caMessageButton_0->setObjectName(QString::fromUtf8("caMessageButton_0"));
        caMessageButton_0->setGeometry(QRect(169, 187, 15, 20));
        caMessageButton_0->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_0->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_0->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_0->setColorMode(caMessageButton::Static);
        caMessageButton_1 = new caMessageButton(centralWidget);
        caMessageButton_1->setObjectName(QString::fromUtf8("caMessageButton_1"));
        caMessageButton_1->setGeometry(QRect(77, 187, 15, 20));
        caMessageButton_1->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_1->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_1->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_1->setColorMode(caMessageButton::Static);
        caTextEntry_0 = new caTextEntry(centralWidget);
        caTextEntry_0->setObjectName(QString::fromUtf8("caTextEntry_0"));
        caTextEntry_0->setGeometry(QRect(93, 187, 76, 20));
        caTextEntry_0->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_0->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_0->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_0->setLimitsMode(caLineEdit::Channel);
        caTextEntry_0->setLimitsMode(caLineEdit::Channel);
        caTextEntry_0->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_0->setMinValue(0);
        caTextEntry_0->setMaxValue(1);
        caTextEntry_0->setColorMode(caLineEdit::Static);
        caTextEntry_0->setFormatType(caTextEntry::decimal);
        caMessageButton_2 = new caMessageButton(centralWidget);
        caMessageButton_2->setObjectName(QString::fromUtf8("caMessageButton_2"));
        caMessageButton_2->setGeometry(QRect(192, 160, 45, 20));
        caMessageButton_2->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_2->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_2->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_2->setColorMode(caMessageButton::Static);
        caMessageButton_3 = new caMessageButton(centralWidget);
        caMessageButton_3->setObjectName(QString::fromUtf8("caMessageButton_3"));
        caMessageButton_3->setGeometry(QRect(242, 160, 45, 20));
        caMessageButton_3->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_3->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_3->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_3->setColorMode(caMessageButton::Static);
        caTextEntry_1 = new caTextEntry(centralWidget);
        caTextEntry_1->setObjectName(QString::fromUtf8("caTextEntry_1"));
        caTextEntry_1->setGeometry(QRect(83, 160, 100, 25));
        caTextEntry_1->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_1->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_1->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_1->setLimitsMode(caLineEdit::Channel);
        caTextEntry_1->setLimitsMode(caLineEdit::Channel);
        caTextEntry_1->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_1->setMinValue(0);
        caTextEntry_1->setMaxValue(1);
        caTextEntry_1->setColorMode(caLineEdit::Static);
        caTextEntry_1->setFormatType(caTextEntry::decimal);
        caMessageButton_4 = new caMessageButton(centralWidget);
        caMessageButton_4->setObjectName(QString::fromUtf8("caMessageButton_4"));
        caMessageButton_4->setGeometry(QRect(242, 185, 45, 20));
        caMessageButton_4->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_4->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_4->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_4->setColorMode(caMessageButton::Static);
        caMessageButton_5 = new caMessageButton(centralWidget);
        caMessageButton_5->setObjectName(QString::fromUtf8("caMessageButton_5"));
        caMessageButton_5->setGeometry(QRect(191, 185, 45, 20));
        caMessageButton_5->setFontScaleMode(EPushButton::WidthAndHeight);
        caMessageButton_5->setForeground(QColor(0, 0, 0, 255));
        caMessageButton_5->setBackground(QColor(115, 223, 255, 255));
        caMessageButton_5->setColorMode(caMessageButton::Static);
        caLabel_7 = new caLabel(centralWidget);
        caLabel_7->setObjectName(QString::fromUtf8("caLabel_7"));
        caLabel_7->setFrameShape(QFrame::NoFrame);
        caLabel_7->setForeground(QColor(0, 0, 0, 255));
        caLabel_7->setBackground(QColor(0, 0, 0, 0));
        caLabel_7->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_7->setGeometry(QRect(305, 315, 32, 18));
        caLabel_7->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_8 = new caLabel(centralWidget);
        caLabel_8->setObjectName(QString::fromUtf8("caLabel_8"));
        caLabel_8->setFrameShape(QFrame::NoFrame);
        caLabel_8->setForeground(QColor(0, 0, 0, 255));
        caLabel_8->setBackground(QColor(0, 0, 0, 0));
        caLabel_8->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_8->setGeometry(QRect(305, 278, 32, 18));
        caLabel_8->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_9 = new caLabel(centralWidget);
        caLabel_9->setObjectName(QString::fromUtf8("caLabel_9"));
        caLabel_9->setFrameShape(QFrame::NoFrame);
        caLabel_9->setForeground(QColor(255, 255, 255, 255));
        caLabel_9->setBackground(QColor(255, 255, 255, 0));
        caLabel_9->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_9->setGeometry(QRect(305, 255, 118, 18));
        caLabel_9->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caChoice_0 = new caChoice(centralWidget);
        caChoice_0->setObjectName(QString::fromUtf8("caChoice_0"));
        caChoice_0->setGeometry(QRect(336, 276, 100, 21));
        caChoice_0->setForeground(QColor(0, 0, 0, 255));
        caChoice_0->setBackground(QColor(115, 223, 255, 255));
        caChoice_0->setStackingMode(caChoice::Column);
        caChoice_0->setColorMode(caChoice::Static);
        caTextEntry_2 = new caTextEntry(centralWidget);
        caTextEntry_2->setObjectName(QString::fromUtf8("caTextEntry_2"));
        caTextEntry_2->setGeometry(QRect(336, 299, 100, 25));
        caTextEntry_2->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_2->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_2->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_2->setLimitsMode(caLineEdit::Channel);
        caTextEntry_2->setLimitsMode(caLineEdit::Channel);
        caTextEntry_2->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_2->setMinValue(0);
        caTextEntry_2->setMaxValue(1);
        caTextEntry_2->setColorMode(caLineEdit::Static);
        caTextEntry_2->setFormatType(caTextEntry::decimal);
        caFrame_0 = new caFrame(centralWidget);
        caFrame_0->setObjectName(QString::fromUtf8("caFrame_0"));
        caFrame_0->setGeometry(QRect(305, 350, 133, 23));
        caLabel_10 = new caLabel(caFrame_0);
        caLabel_10->setObjectName(QString::fromUtf8("caLabel_10"));
        caLabel_10->setFrameShape(QFrame::NoFrame);
        caLabel_10->setForeground(QColor(0, 0, 0, 255));
        caLabel_10->setBackground(QColor(0, 0, 0, 0));
        caLabel_10->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_10->setGeometry(QRect(0, 3, 32, 18));
        caLabel_10->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caChoice_1 = new caChoice(caFrame_0);
        caChoice_1->setObjectName(QString::fromUtf8("caChoice_1"));
        caChoice_1->setGeometry(QRect(31, 0, 100, 21));
        caChoice_1->setForeground(QColor(0, 0, 0, 255));
        caChoice_1->setBackground(QColor(115, 223, 255, 255));
        caChoice_1->setStackingMode(caChoice::Column);
        caChoice_1->setColorMode(caChoice::Static);
        caTextEntry_3 = new caTextEntry(centralWidget);
        caTextEntry_3->setObjectName(QString::fromUtf8("caTextEntry_3"));
        caTextEntry_3->setGeometry(QRect(190, 290, 100, 25));
        caTextEntry_3->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_3->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_3->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_3->setLimitsMode(caLineEdit::Channel);
        caTextEntry_3->setLimitsMode(caLineEdit::Channel);
        caTextEntry_3->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_3->setMinValue(0);
        caTextEntry_3->setMaxValue(1);
        caTextEntry_3->setColorMode(caLineEdit::Static);
        caTextEntry_3->setFormatType(caTextEntry::decimal);
        caTextEntry_4 = new caTextEntry(centralWidget);
        caTextEntry_4->setObjectName(QString::fromUtf8("caTextEntry_4"));
        caTextEntry_4->setGeometry(QRect(87, 290, 100, 25));
        caTextEntry_4->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_4->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_4->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_4->setLimitsMode(caLineEdit::Channel);
        caTextEntry_4->setLimitsMode(caLineEdit::Channel);
        caTextEntry_4->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_4->setMinValue(0);
        caTextEntry_4->setMaxValue(1);
        caTextEntry_4->setColorMode(caLineEdit::Static);
        caTextEntry_4->setFormatType(caTextEntry::decimal);
        caLabel_11 = new caLabel(centralWidget);
        caLabel_11->setObjectName(QString::fromUtf8("caLabel_11"));
        caLabel_11->setFrameShape(QFrame::NoFrame);
        caLabel_11->setForeground(QColor(0, 0, 0, 255));
        caLabel_11->setBackground(QColor(0, 0, 0, 0));
        caLabel_11->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_11->setGeometry(QRect(2, 293, 73, 18));
        caLabel_11->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_5 = new caTextEntry(centralWidget);
        caTextEntry_5->setObjectName(QString::fromUtf8("caTextEntry_5"));
        caTextEntry_5->setGeometry(QRect(190, 315, 100, 25));
        caTextEntry_5->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_5->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_5->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_5->setLimitsMode(caLineEdit::Channel);
        caTextEntry_5->setLimitsMode(caLineEdit::Channel);
        caTextEntry_5->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_5->setMinValue(0);
        caTextEntry_5->setMaxValue(1);
        caTextEntry_5->setColorMode(caLineEdit::Static);
        caTextEntry_5->setFormatType(caTextEntry::decimal);
        caLabel_12 = new caLabel(centralWidget);
        caLabel_12->setObjectName(QString::fromUtf8("caLabel_12"));
        caLabel_12->setFrameShape(QFrame::NoFrame);
        caLabel_12->setForeground(QColor(0, 0, 0, 255));
        caLabel_12->setBackground(QColor(0, 0, 0, 0));
        caLabel_12->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_12->setGeometry(QRect(2, 318, 183, 18));
        caLabel_12->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_6 = new caTextEntry(centralWidget);
        caTextEntry_6->setObjectName(QString::fromUtf8("caTextEntry_6"));
        caTextEntry_6->setGeometry(QRect(190, 340, 100, 25));
        caTextEntry_6->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_6->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_6->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_6->setLimitsMode(caLineEdit::Channel);
        caTextEntry_6->setLimitsMode(caLineEdit::Channel);
        caTextEntry_6->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_6->setMinValue(0);
        caTextEntry_6->setMaxValue(1);
        caTextEntry_6->setColorMode(caLineEdit::Static);
        caTextEntry_6->setFormatType(caTextEntry::decimal);
        caLabel_13 = new caLabel(centralWidget);
        caLabel_13->setObjectName(QString::fromUtf8("caLabel_13"));
        caLabel_13->setFrameShape(QFrame::NoFrame);
        caLabel_13->setForeground(QColor(0, 0, 0, 255));
        caLabel_13->setBackground(QColor(0, 0, 0, 0));
        caLabel_13->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_13->setGeometry(QRect(2, 343, 177, 18));
        caLabel_13->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_14 = new caLabel(centralWidget);
        caLabel_14->setObjectName(QString::fromUtf8("caLabel_14"));
        caLabel_14->setFrameShape(QFrame::NoFrame);
        caLabel_14->setForeground(QColor(0, 0, 0, 255));
        caLabel_14->setBackground(QColor(0, 0, 0, 0));
        caLabel_14->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_14->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_14->setGeometry(QRect(98, 25, 73, 18));
        caLabel_15 = new caLabel(centralWidget);
        caLabel_15->setObjectName(QString::fromUtf8("caLabel_15"));
        caLabel_15->setFrameShape(QFrame::NoFrame);
        caLabel_15->setForeground(QColor(0, 0, 0, 255));
        caLabel_15->setBackground(QColor(0, 0, 0, 0));
        caLabel_15->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_15->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_15->setGeometry(QRect(196, 25, 73, 18));
        caTextEntry_7 = new caTextEntry(centralWidget);
        caTextEntry_7->setObjectName(QString::fromUtf8("caTextEntry_7"));
        caTextEntry_7->setGeometry(QRect(87, 240, 100, 25));
        caTextEntry_7->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_7->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_7->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_7->setLimitsMode(caLineEdit::Channel);
        caTextEntry_7->setLimitsMode(caLineEdit::Channel);
        caTextEntry_7->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_7->setMinValue(0);
        caTextEntry_7->setMaxValue(1);
        caTextEntry_7->setColorMode(caLineEdit::Static);
        caTextEntry_7->setFormatType(caTextEntry::decimal);
        caLabel_16 = new caLabel(centralWidget);
        caLabel_16->setObjectName(QString::fromUtf8("caLabel_16"));
        caLabel_16->setFrameShape(QFrame::NoFrame);
        caLabel_16->setForeground(QColor(0, 0, 0, 255));
        caLabel_16->setBackground(QColor(0, 0, 0, 0));
        caLabel_16->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_16->setGeometry(QRect(2, 243, 73, 18));
        caLabel_16->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_17 = new caLabel(centralWidget);
        caLabel_17->setObjectName(QString::fromUtf8("caLabel_17"));
        caLabel_17->setFrameShape(QFrame::NoFrame);
        caLabel_17->setForeground(QColor(0, 0, 0, 255));
        caLabel_17->setBackground(QColor(0, 0, 0, 0));
        caLabel_17->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_17->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_17->setGeometry(QRect(101, 220, 73, 18));
        caLabel_18 = new caLabel(centralWidget);
        caLabel_18->setObjectName(QString::fromUtf8("caLabel_18"));
        caLabel_18->setFrameShape(QFrame::NoFrame);
        caLabel_18->setForeground(QColor(0, 0, 0, 255));
        caLabel_18->setBackground(QColor(0, 0, 0, 0));
        caLabel_18->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_18->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_18->setGeometry(QRect(200, 220, 86, 18));
        caTextEntry_8 = new caTextEntry(centralWidget);
        caTextEntry_8->setObjectName(QString::fromUtf8("caTextEntry_8"));
        caTextEntry_8->setGeometry(QRect(140, 400, 100, 25));
        caTextEntry_8->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_8->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_8->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_8->setLimitsMode(caLineEdit::Channel);
        caTextEntry_8->setLimitsMode(caLineEdit::Channel);
        caTextEntry_8->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_8->setMinValue(0);
        caTextEntry_8->setMaxValue(1);
        caTextEntry_8->setColorMode(caLineEdit::Static);
        caTextEntry_8->setFormatType(caTextEntry::decimal);
        caLabel_19 = new caLabel(centralWidget);
        caLabel_19->setObjectName(QString::fromUtf8("caLabel_19"));
        caLabel_19->setFrameShape(QFrame::NoFrame);
        caLabel_19->setForeground(QColor(0, 0, 0, 255));
        caLabel_19->setBackground(QColor(0, 0, 0, 0));
        caLabel_19->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_19->setGeometry(QRect(2, 403, 125, 18));
        caLabel_19->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_9 = new caTextEntry(centralWidget);
        caTextEntry_9->setObjectName(QString::fromUtf8("caTextEntry_9"));
        caTextEntry_9->setGeometry(QRect(140, 425, 100, 25));
        caTextEntry_9->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_9->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_9->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_9->setLimitsMode(caLineEdit::Channel);
        caTextEntry_9->setLimitsMode(caLineEdit::Channel);
        caTextEntry_9->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_9->setMinValue(0);
        caTextEntry_9->setMaxValue(1);
        caTextEntry_9->setColorMode(caLineEdit::Static);
        caTextEntry_9->setFormatType(caTextEntry::decimal);
        caLabel_20 = new caLabel(centralWidget);
        caLabel_20->setObjectName(QString::fromUtf8("caLabel_20"));
        caLabel_20->setFrameShape(QFrame::NoFrame);
        caLabel_20->setForeground(QColor(0, 0, 0, 255));
        caLabel_20->setBackground(QColor(0, 0, 0, 0));
        caLabel_20->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_20->setGeometry(QRect(2, 428, 129, 18));
        caLabel_20->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_10 = new caTextEntry(centralWidget);
        caTextEntry_10->setObjectName(QString::fromUtf8("caTextEntry_10"));
        caTextEntry_10->setGeometry(QRect(140, 475, 100, 25));
        caTextEntry_10->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_10->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_10->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_10->setLimitsMode(caLineEdit::Channel);
        caTextEntry_10->setLimitsMode(caLineEdit::Channel);
        caTextEntry_10->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_10->setMinValue(0);
        caTextEntry_10->setMaxValue(1);
        caTextEntry_10->setColorMode(caLineEdit::Static);
        caTextEntry_10->setFormatType(caTextEntry::decimal);
        caLabel_21 = new caLabel(centralWidget);
        caLabel_21->setObjectName(QString::fromUtf8("caLabel_21"));
        caLabel_21->setFrameShape(QFrame::NoFrame);
        caLabel_21->setForeground(QColor(0, 0, 0, 255));
        caLabel_21->setBackground(QColor(0, 0, 0, 0));
        caLabel_21->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_21->setGeometry(QRect(2, 478, 151, 18));
        caLabel_21->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_11 = new caTextEntry(centralWidget);
        caTextEntry_11->setObjectName(QString::fromUtf8("caTextEntry_11"));
        caTextEntry_11->setGeometry(QRect(170, 500, 50, 25));
        caTextEntry_11->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_11->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_11->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_11->setLimitsMode(caLineEdit::Channel);
        caTextEntry_11->setLimitsMode(caLineEdit::Channel);
        caTextEntry_11->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_11->setMinValue(0);
        caTextEntry_11->setMaxValue(1);
        caTextEntry_11->setColorMode(caLineEdit::Static);
        caTextEntry_11->setFormatType(caTextEntry::decimal);
        caLabel_22 = new caLabel(centralWidget);
        caLabel_22->setObjectName(QString::fromUtf8("caLabel_22"));
        caLabel_22->setFrameShape(QFrame::NoFrame);
        caLabel_22->setForeground(QColor(0, 0, 0, 255));
        caLabel_22->setBackground(QColor(0, 0, 0, 0));
        caLabel_22->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_22->setGeometry(QRect(131, 503, 44, 18));
        caLabel_22->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_0 = new caLineEdit(centralWidget);
        caLineEdit_0->setObjectName(QString::fromUtf8("caLineEdit_0"));
        caLineEdit_0->setGeometry(QRect(73, 503, 50, 18));
        caLineEdit_0->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_0->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_0->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_0->setLimitsMode(caLineEdit::Channel);
        caLineEdit_0->setLimitsMode(caLineEdit::Channel);
        caLineEdit_0->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_0->setMinValue(0);
        caLineEdit_0->setMaxValue(1);
        caLineEdit_0->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_0->setFormatType(caLineEdit::decimal);
        caLineEdit_0->setColorMode(caLineEdit::Static);
        caLabel_23 = new caLabel(centralWidget);
        caLabel_23->setObjectName(QString::fromUtf8("caLabel_23"));
        caLabel_23->setFrameShape(QFrame::NoFrame);
        caLabel_23->setForeground(QColor(0, 0, 0, 255));
        caLabel_23->setBackground(QColor(0, 0, 0, 0));
        caLabel_23->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_23->setGeometry(QRect(4, 503, 75, 18));
        caLabel_23->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_24 = new caLabel(centralWidget);
        caLabel_24->setObjectName(QString::fromUtf8("caLabel_24"));
        caLabel_24->setFrameShape(QFrame::NoFrame);
        caLabel_24->setForeground(QColor(0, 0, 0, 255));
        caLabel_24->setBackground(QColor(0, 0, 0, 0));
        caLabel_24->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_24->setGeometry(QRect(255, 420, 75, 18));
        caLabel_24->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_1 = new caLineEdit(centralWidget);
        caLineEdit_1->setObjectName(QString::fromUtf8("caLineEdit_1"));
        caLineEdit_1->setGeometry(QRect(333, 420, 100, 18));
        caLineEdit_1->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_1->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_1->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_1->setLimitsMode(caLineEdit::Channel);
        caLineEdit_1->setLimitsMode(caLineEdit::Channel);
        caLineEdit_1->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_1->setMinValue(0);
        caLineEdit_1->setMaxValue(1);
        caLineEdit_1->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_1->setFormatType(caLineEdit::decimal);
        caLineEdit_1->setColorMode(caLineEdit::Static);
        caLabel_25 = new caLabel(centralWidget);
        caLabel_25->setObjectName(QString::fromUtf8("caLabel_25"));
        caLabel_25->setFrameShape(QFrame::NoFrame);
        caLabel_25->setForeground(QColor(0, 0, 0, 255));
        caLabel_25->setBackground(QColor(0, 0, 0, 0));
        caLabel_25->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_25->setGeometry(QRect(255, 440, 73, 18));
        caLabel_25->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_2 = new caLineEdit(centralWidget);
        caLineEdit_2->setObjectName(QString::fromUtf8("caLineEdit_2"));
        caLineEdit_2->setGeometry(QRect(333, 440, 100, 18));
        caLineEdit_2->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_2->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_2->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_2->setLimitsMode(caLineEdit::Channel);
        caLineEdit_2->setLimitsMode(caLineEdit::Channel);
        caLineEdit_2->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_2->setMinValue(0);
        caLineEdit_2->setMaxValue(1);
        caLineEdit_2->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_2->setFormatType(caLineEdit::decimal);
        caLineEdit_2->setColorMode(caLineEdit::Static);
        caLineEdit_3 = new caLineEdit(centralWidget);
        caLineEdit_3->setObjectName(QString::fromUtf8("caLineEdit_3"));
        caLineEdit_3->setGeometry(QRect(333, 400, 100, 18));
        caLineEdit_3->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_3->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_3->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_3->setLimitsMode(caLineEdit::Channel);
        caLineEdit_3->setLimitsMode(caLineEdit::Channel);
        caLineEdit_3->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_3->setMinValue(0);
        caLineEdit_3->setMaxValue(1);
        caLineEdit_3->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_3->setFormatType(caLineEdit::hexadecimal);
        caLineEdit_3->setColorMode(caLineEdit::Static);
        caLabel_26 = new caLabel(centralWidget);
        caLabel_26->setObjectName(QString::fromUtf8("caLabel_26"));
        caLabel_26->setFrameShape(QFrame::NoFrame);
        caLabel_26->setForeground(QColor(0, 0, 0, 255));
        caLabel_26->setBackground(QColor(0, 0, 0, 0));
        caLabel_26->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_26->setGeometry(QRect(255, 400, 97, 18));
        caLabel_26->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_27 = new caLabel(centralWidget);
        caLabel_27->setObjectName(QString::fromUtf8("caLabel_27"));
        caLabel_27->setFrameShape(QFrame::NoFrame);
        caLabel_27->setForeground(QColor(0, 0, 0, 255));
        caLabel_27->setBackground(QColor(0, 0, 0, 0));
        caLabel_27->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_27->setGeometry(QRect(255, 460, 75, 18));
        caLabel_27->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_28 = new caLabel(centralWidget);
        caLabel_28->setObjectName(QString::fromUtf8("caLabel_28"));
        caLabel_28->setFrameShape(QFrame::NoFrame);
        caLabel_28->setForeground(QColor(0, 0, 0, 255));
        caLabel_28->setBackground(QColor(0, 0, 0, 0));
        caLabel_28->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_28->setGeometry(QRect(255, 500, 75, 18));
        caLabel_28->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_29 = new caLabel(centralWidget);
        caLabel_29->setObjectName(QString::fromUtf8("caLabel_29"));
        caLabel_29->setFrameShape(QFrame::NoFrame);
        caLabel_29->setForeground(QColor(0, 0, 0, 255));
        caLabel_29->setBackground(QColor(0, 0, 0, 0));
        caLabel_29->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_29->setGeometry(QRect(255, 480, 86, 18));
        caLabel_29->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_30 = new caLabel(centralWidget);
        caLabel_30->setObjectName(QString::fromUtf8("caLabel_30"));
        caLabel_30->setFrameShape(QFrame::NoFrame);
        caLabel_30->setForeground(QColor(0, 0, 0, 255));
        caLabel_30->setBackground(QColor(0, 0, 0, 0));
        caLabel_30->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_30->setGeometry(QRect(255, 520, 97, 18));
        caLabel_30->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_4 = new caLineEdit(centralWidget);
        caLineEdit_4->setObjectName(QString::fromUtf8("caLineEdit_4"));
        caLineEdit_4->setGeometry(QRect(333, 540, 100, 18));
        caLineEdit_4->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_4->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_4->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_4->setLimitsMode(caLineEdit::Channel);
        caLineEdit_4->setLimitsMode(caLineEdit::Channel);
        caLineEdit_4->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_4->setMinValue(0);
        caLineEdit_4->setMaxValue(1);
        caLineEdit_4->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_4->setFormatType(caLineEdit::decimal);
        caLineEdit_4->setColorMode(caLineEdit::Static);
        caLabel_31 = new caLabel(centralWidget);
        caLabel_31->setObjectName(QString::fromUtf8("caLabel_31"));
        caLabel_31->setFrameShape(QFrame::NoFrame);
        caLabel_31->setForeground(QColor(0, 0, 0, 255));
        caLabel_31->setBackground(QColor(0, 0, 0, 0));
        caLabel_31->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_31->setGeometry(QRect(254, 540, 73, 18));
        caLabel_31->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_5 = new caLineEdit(centralWidget);
        caLineEdit_5->setObjectName(QString::fromUtf8("caLineEdit_5"));
        caLineEdit_5->setGeometry(QRect(333, 460, 100, 18));
        caLineEdit_5->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_5->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_5->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_5->setLimitsMode(caLineEdit::Channel);
        caLineEdit_5->setLimitsMode(caLineEdit::Channel);
        caLineEdit_5->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_5->setMinValue(0);
        caLineEdit_5->setMaxValue(1);
        caLineEdit_5->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_5->setFormatType(caLineEdit::decimal);
        caLineEdit_5->setColorMode(caLineEdit::Static);
        caLineEdit_6 = new caLineEdit(centralWidget);
        caLineEdit_6->setObjectName(QString::fromUtf8("caLineEdit_6"));
        caLineEdit_6->setGeometry(QRect(333, 500, 100, 18));
        caLineEdit_6->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_6->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_6->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_6->setLimitsMode(caLineEdit::Channel);
        caLineEdit_6->setLimitsMode(caLineEdit::Channel);
        caLineEdit_6->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_6->setMinValue(0);
        caLineEdit_6->setMaxValue(1);
        caLineEdit_6->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_6->setFormatType(caLineEdit::decimal);
        caLineEdit_6->setColorMode(caLineEdit::Static);
        caLineEdit_7 = new caLineEdit(centralWidget);
        caLineEdit_7->setObjectName(QString::fromUtf8("caLineEdit_7"));
        caLineEdit_7->setGeometry(QRect(333, 480, 100, 18));
        caLineEdit_7->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_7->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_7->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_7->setLimitsMode(caLineEdit::Channel);
        caLineEdit_7->setLimitsMode(caLineEdit::Channel);
        caLineEdit_7->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_7->setMinValue(0);
        caLineEdit_7->setMaxValue(1);
        caLineEdit_7->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_7->setFormatType(caLineEdit::decimal);
        caLineEdit_7->setColorMode(caLineEdit::Static);
        caLineEdit_8 = new caLineEdit(centralWidget);
        caLineEdit_8->setObjectName(QString::fromUtf8("caLineEdit_8"));
        caLineEdit_8->setGeometry(QRect(333, 520, 100, 18));
        caLineEdit_8->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_8->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_8->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_8->setLimitsMode(caLineEdit::Channel);
        caLineEdit_8->setLimitsMode(caLineEdit::Channel);
        caLineEdit_8->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_8->setMinValue(0);
        caLineEdit_8->setMaxValue(1);
        caLineEdit_8->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_8->setFormatType(caLineEdit::hexadecimal);
        caLineEdit_8->setColorMode(caLineEdit::Static);
        caLabel_32 = new caLabel(centralWidget);
        caLabel_32->setObjectName(QString::fromUtf8("caLabel_32"));
        caLabel_32->setFrameShape(QFrame::NoFrame);
        caLabel_32->setForeground(QColor(0, 0, 0, 255));
        caLabel_32->setBackground(QColor(0, 0, 0, 0));
        caLabel_32->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_32->setGeometry(QRect(2, 593, 73, 18));
        caLabel_32->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caChoice_2 = new caChoice(centralWidget);
        caChoice_2->setObjectName(QString::fromUtf8("caChoice_2"));
        caChoice_2->setGeometry(QRect(140, 525, 100, 25));
        caChoice_2->setForeground(QColor(0, 0, 0, 255));
        caChoice_2->setBackground(QColor(115, 223, 255, 255));
        caChoice_2->setStackingMode(caChoice::Column);
        caChoice_2->setColorMode(caChoice::Static);
        caLabel_33 = new caLabel(centralWidget);
        caLabel_33->setObjectName(QString::fromUtf8("caLabel_33"));
        caLabel_33->setFrameShape(QFrame::NoFrame);
        caLabel_33->setForeground(QColor(0, 0, 0, 255));
        caLabel_33->setBackground(QColor(0, 0, 0, 0));
        caLabel_33->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_33->setGeometry(QRect(2, 528, 118, 18));
        caLabel_33->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caChoice_3 = new caChoice(centralWidget);
        caChoice_3->setObjectName(QString::fromUtf8("caChoice_3"));
        caChoice_3->setGeometry(QRect(140, 550, 100, 25));
        caChoice_3->setForeground(QColor(0, 0, 0, 255));
        caChoice_3->setBackground(QColor(115, 223, 255, 255));
        caChoice_3->setStackingMode(caChoice::Column);
        caChoice_3->setColorMode(caChoice::Static);
        caLabel_34 = new caLabel(centralWidget);
        caLabel_34->setObjectName(QString::fromUtf8("caLabel_34"));
        caLabel_34->setFrameShape(QFrame::NoFrame);
        caLabel_34->setForeground(QColor(0, 0, 0, 255));
        caLabel_34->setBackground(QColor(0, 0, 0, 0));
        caLabel_34->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_34->setGeometry(QRect(2, 553, 129, 18));
        caLabel_34->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_12 = new caTextEntry(centralWidget);
        caTextEntry_12->setObjectName(QString::fromUtf8("caTextEntry_12"));
        caTextEntry_12->setGeometry(QRect(140, 450, 100, 25));
        caTextEntry_12->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_12->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_12->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_12->setLimitsMode(caLineEdit::Channel);
        caTextEntry_12->setLimitsMode(caLineEdit::Channel);
        caTextEntry_12->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_12->setMinValue(0);
        caTextEntry_12->setMaxValue(1);
        caTextEntry_12->setColorMode(caLineEdit::Static);
        caTextEntry_12->setFormatType(caTextEntry::decimal);
        caLabel_35 = new caLabel(centralWidget);
        caLabel_35->setObjectName(QString::fromUtf8("caLabel_35"));
        caLabel_35->setFrameShape(QFrame::NoFrame);
        caLabel_35->setForeground(QColor(0, 0, 0, 255));
        caLabel_35->setBackground(QColor(0, 0, 0, 0));
        caLabel_35->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_35->setGeometry(QRect(2, 453, 140, 18));
        caLabel_35->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_36 = new caLabel(centralWidget);
        caLabel_36->setObjectName(QString::fromUtf8("caLabel_36"));
        caLabel_36->setFrameShape(QFrame::NoFrame);
        caLabel_36->setForeground(QColor(0, 0, 0, 255));
        caLabel_36->setBackground(QColor(0, 0, 0, 0));
        caLabel_36->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_36->setGeometry(QRect(254, 578, 97, 18));
        caLabel_36->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caChoice_4 = new caChoice(centralWidget);
        caChoice_4->setObjectName(QString::fromUtf8("caChoice_4"));
        caChoice_4->setGeometry(QRect(35, 584, 100, 37));
        caChoice_4->setForeground(QColor(0, 0, 0, 255));
        caChoice_4->setBackground(QColor(115, 223, 255, 255));
        caChoice_4->setColorMode(caChoice::Static);
        caChoice_5 = new caChoice(centralWidget);
        caChoice_5->setObjectName(QString::fromUtf8("caChoice_5"));
        caChoice_5->setGeometry(QRect(140, 584, 100, 37));
        caChoice_5->setForeground(QColor(0, 0, 0, 255));
        caChoice_5->setBackground(QColor(115, 223, 255, 255));
        caChoice_5->setColorMode(caChoice::Static);
        caLabel_37 = new caLabel(centralWidget);
        caLabel_37->setObjectName(QString::fromUtf8("caLabel_37"));
        caLabel_37->setFrameShape(QFrame::NoFrame);
        caLabel_37->setForeground(QColor(255, 255, 255, 255));
        caLabel_37->setBackground(QColor(255, 255, 255, 0));
        caLabel_37->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_37->setGeometry(QRect(1, 220, 86, 18));
        caLabel_37->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_38 = new caLabel(centralWidget);
        caLabel_38->setObjectName(QString::fromUtf8("caLabel_38"));
        caLabel_38->setFrameShape(QFrame::NoFrame);
        caLabel_38->setForeground(QColor(0, 0, 0, 255));
        caLabel_38->setBackground(QColor(0, 0, 0, 0));
        caLabel_38->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_38->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_38->setGeometry(QRect(340, 25, 73, 18));
        caLabel_39 = new caLabel(centralWidget);
        caLabel_39->setObjectName(QString::fromUtf8("caLabel_39"));
        caLabel_39->setFrameShape(QFrame::NoFrame);
        caLabel_39->setForeground(QColor(0, 0, 0, 255));
        caLabel_39->setBackground(QColor(0, 0, 0, 0));
        caLabel_39->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_39->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_39->setGeometry(QRect(285, 25, 32, 18));
        caLabel_40 = new caLabel(centralWidget);
        caLabel_40->setObjectName(QString::fromUtf8("caLabel_40"));
        caLabel_40->setFrameShape(QFrame::NoFrame);
        caLabel_40->setForeground(QColor(255, 255, 255, 255));
        caLabel_40->setBackground(QColor(255, 255, 255, 0));
        caLabel_40->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_40->setGeometry(QRect(2, 25, 73, 18));
        caLabel_40->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_41 = new caLabel(centralWidget);
        caLabel_41->setObjectName(QString::fromUtf8("caLabel_41"));
        caLabel_41->setFrameShape(QFrame::NoFrame);
        caLabel_41->setForeground(QColor(10, 0, 184, 255));
        caLabel_41->setBackground(QColor(10, 0, 184, 0));
        caLabel_41->setVisibility(caLabel::IfNotZero);
        caLabel_41->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_41->setGeometry(QRect(290, 77, 46, 13));
        caLabel_41->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_42 = new caLabel(centralWidget);
        caLabel_42->setObjectName(QString::fromUtf8("caLabel_42"));
        caLabel_42->setFrameShape(QFrame::NoFrame);
        caLabel_42->setForeground(QColor(10, 0, 184, 255));
        caLabel_42->setBackground(QColor(10, 0, 184, 0));
        caLabel_42->setVisibility(caLabel::IfNotZero);
        caLabel_42->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_42->setGeometry(QRect(289, 67, 40, 13));
        caLabel_42->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_9 = new caLineEdit(centralWidget);
        caLineEdit_9->setObjectName(QString::fromUtf8("caLineEdit_9"));
        caLineEdit_9->setGeometry(QRect(83, 72, 100, 18));
        caLineEdit_9->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_9->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_9->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_9->setLimitsMode(caLineEdit::Channel);
        caLineEdit_9->setLimitsMode(caLineEdit::Channel);
        caLineEdit_9->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_9->setMinValue(0);
        caLineEdit_9->setMaxValue(1);
        caLineEdit_9->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_9->setFormatType(caLineEdit::decimal);
        caLineEdit_9->setColorMode(caLineEdit::Static);
        caLineEdit_10 = new caLineEdit(centralWidget);
        caLineEdit_10->setObjectName(QString::fromUtf8("caLineEdit_10"));
        caLineEdit_10->setGeometry(QRect(187, 72, 100, 18));
        caLineEdit_10->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_10->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_10->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_10->setLimitsMode(caLineEdit::Channel);
        caLineEdit_10->setLimitsMode(caLineEdit::Channel);
        caLineEdit_10->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_10->setMinValue(0);
        caLineEdit_10->setMaxValue(1);
        caLineEdit_10->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_10->setFormatType(caLineEdit::decimal);
        caLineEdit_10->setColorMode(caLineEdit::Static);
        caLineEdit_11 = new caLineEdit(centralWidget);
        caLineEdit_11->setObjectName(QString::fromUtf8("caLineEdit_11"));
        caLineEdit_11->setGeometry(QRect(335, 71, 100, 19));
        caLineEdit_11->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_11->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_11->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_11->setLimitsMode(caLineEdit::Channel);
        caLineEdit_11->setLimitsMode(caLineEdit::Channel);
        caLineEdit_11->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_11->setMinValue(0);
        caLineEdit_11->setMaxValue(1);
        caLineEdit_11->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_11->setFormatType(caLineEdit::decimal);
        caLineEdit_11->setColorMode(caLineEdit::Static);
        caTextEntry_13 = new caTextEntry(centralWidget);
        caTextEntry_13->setObjectName(QString::fromUtf8("caTextEntry_13"));
        caTextEntry_13->setGeometry(QRect(83, 96, 100, 25));
        caTextEntry_13->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_13->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_13->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_13->setLimitsMode(caLineEdit::Channel);
        caTextEntry_13->setLimitsMode(caLineEdit::Channel);
        caTextEntry_13->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_13->setMinValue(0);
        caTextEntry_13->setMaxValue(1);
        caTextEntry_13->setColorMode(caLineEdit::Static);
        caTextEntry_13->setFormatType(caTextEntry::decimal);
        caTextEntry_14 = new caTextEntry(centralWidget);
        caTextEntry_14->setObjectName(QString::fromUtf8("caTextEntry_14"));
        caTextEntry_14->setGeometry(QRect(83, 123, 100, 25));
        caTextEntry_14->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_14->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_14->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_14->setLimitsMode(caLineEdit::Channel);
        caTextEntry_14->setLimitsMode(caLineEdit::Channel);
        caTextEntry_14->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_14->setMinValue(0);
        caTextEntry_14->setMaxValue(1);
        caTextEntry_14->setColorMode(caLineEdit::Static);
        caTextEntry_14->setFormatType(caTextEntry::decimal);
        caFrame_1 = new caFrame(centralWidget);
        caFrame_1->setObjectName(QString::fromUtf8("caFrame_1"));
        caFrame_1->setGeometry(QRect(83, 44, 206, 27));
        caTextEntry_15 = new caTextEntry(caFrame_1);
        caTextEntry_15->setObjectName(QString::fromUtf8("caTextEntry_15"));
        caTextEntry_15->setGeometry(QRect(104, 0, 100, 25));
        caTextEntry_15->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_15->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_15->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_15->setLimitsMode(caLineEdit::Channel);
        caTextEntry_15->setLimitsMode(caLineEdit::Channel);
        caTextEntry_15->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_15->setMinValue(0);
        caTextEntry_15->setMaxValue(1);
        caTextEntry_15->setColorMode(caLineEdit::Static);
        caTextEntry_15->setFormatType(caTextEntry::decimal);
        caTextEntry_16 = new caTextEntry(caFrame_1);
        caTextEntry_16->setObjectName(QString::fromUtf8("caTextEntry_16"));
        caTextEntry_16->setGeometry(QRect(0, 0, 100, 25));
        caTextEntry_16->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_16->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_16->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_16->setLimitsMode(caLineEdit::Channel);
        caTextEntry_16->setLimitsMode(caLineEdit::Channel);
        caTextEntry_16->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_16->setMinValue(0);
        caTextEntry_16->setMaxValue(1);
        caTextEntry_16->setColorMode(caLineEdit::Static);
        caTextEntry_16->setFormatType(caTextEntry::decimal);
        caTextEntry_17 = new caTextEntry(centralWidget);
        caTextEntry_17->setObjectName(QString::fromUtf8("caTextEntry_17"));
        caTextEntry_17->setGeometry(QRect(187, 96, 100, 25));
        caTextEntry_17->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_17->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_17->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_17->setLimitsMode(caLineEdit::Channel);
        caTextEntry_17->setLimitsMode(caLineEdit::Channel);
        caTextEntry_17->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_17->setMinValue(0);
        caTextEntry_17->setMaxValue(1);
        caTextEntry_17->setColorMode(caLineEdit::Static);
        caTextEntry_17->setFormatType(caTextEntry::decimal);
        caTextEntry_18 = new caTextEntry(centralWidget);
        caTextEntry_18->setObjectName(QString::fromUtf8("caTextEntry_18"));
        caTextEntry_18->setGeometry(QRect(187, 123, 100, 25));
        caTextEntry_18->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_18->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_18->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_18->setLimitsMode(caLineEdit::Channel);
        caTextEntry_18->setLimitsMode(caLineEdit::Channel);
        caTextEntry_18->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_18->setMinValue(0);
        caTextEntry_18->setMaxValue(1);
        caTextEntry_18->setColorMode(caLineEdit::Static);
        caTextEntry_18->setFormatType(caTextEntry::decimal);
        caTextEntry_19 = new caTextEntry(centralWidget);
        caTextEntry_19->setObjectName(QString::fromUtf8("caTextEntry_19"));
        caTextEntry_19->setGeometry(QRect(190, 240, 100, 25));
        caTextEntry_19->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_19->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_19->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_19->setLimitsMode(caLineEdit::Channel);
        caTextEntry_19->setLimitsMode(caLineEdit::Channel);
        caTextEntry_19->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_19->setMinValue(0);
        caTextEntry_19->setMaxValue(1);
        caTextEntry_19->setColorMode(caLineEdit::Static);
        caTextEntry_19->setFormatType(caTextEntry::decimal);
        caChoice_6 = new caChoice(centralWidget);
        caChoice_6->setObjectName(QString::fromUtf8("caChoice_6"));
        caChoice_6->setGeometry(QRect(340, 130, 90, 80));
        caChoice_6->setForeground(QColor(249, 218, 60, 255));
        caChoice_6->setBackground(QColor(253, 0, 0, 255));
        caChoice_6->setColorMode(caChoice::Static);
        caGraphics_0 = new caGraphics(centralWidget);
        caGraphics_0->setObjectName(QString::fromUtf8("caGraphics_0"));
        caGraphics_0->setForm(caGraphics::Circle);
        caGraphics_0->setGeometry(QRect(290, 44, 21, 21));
        caGraphics_0->setForeground(QColor(253, 0, 0, 255));
        caGraphics_0->setFillstyle(caGraphics::Filled);
        caGraphics_0->setLineColor(QColor(253, 0, 0, 255));
        caGraphics_0->setLinestyle(caGraphics::Solid);
        caGraphics_0->setVisibility(caGraphics::IfNotZero);
        caGraphics_1 = new caGraphics(centralWidget);
        caGraphics_1->setObjectName(QString::fromUtf8("caGraphics_1"));
        caGraphics_1->setForm(caGraphics::Circle);
        caGraphics_1->setGeometry(QRect(290, 123, 21, 21));
        caGraphics_1->setForeground(QColor(253, 0, 0, 255));
        caGraphics_1->setFillstyle(caGraphics::Filled);
        caGraphics_1->setLineColor(QColor(253, 0, 0, 255));
        caGraphics_1->setLinestyle(caGraphics::Solid);
        caGraphics_1->setVisibility(caGraphics::IfNotZero);
        caLabel_43 = new caLabel(centralWidget);
        caLabel_43->setObjectName(QString::fromUtf8("caLabel_43"));
        caLabel_43->setFrameShape(QFrame::NoFrame);
        caLabel_43->setForeground(QColor(255, 255, 255, 255));
        caLabel_43->setBackground(QColor(255, 255, 255, 0));
        caLabel_43->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_43->setGeometry(QRect(2, 375, 75, 18));
        caLabel_43->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLabel_44 = new caLabel(centralWidget);
        caLabel_44->setObjectName(QString::fromUtf8("caLabel_44"));
        caLabel_44->setFrameShape(QFrame::NoFrame);
        caLabel_44->setForeground(QColor(255, 255, 255, 255));
        caLabel_44->setBackground(QColor(255, 255, 255, 0));
        caLabel_44->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_44->setGeometry(QRect(255, 375, 75, 18));
        caLabel_44->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caRectangle_2 = new caGraphics(centralWidget);
        caRectangle_2->setObjectName(QString::fromUtf8("caRectangle_2"));
        caRectangle_2->setForm(caGraphics::Rectangle);
        caRectangle_2->setGeometry(QRect(81, 94, 356, 29));
        caRectangle_2->setLineSize(1);
        caRectangle_2->setForeground(QColor(251, 243, 74, 255));
        caRectangle_2->setFillstyle(caGraphics::Filled);
        caRectangle_2->setLineColor(QColor(251, 243, 74, 255));
        caRectangle_2->setLinestyle(caGraphics::Solid);
        caRectangle_2->setVisibility(caGraphics::IfNotZero);
        caLabel_45 = new caLabel(centralWidget);
        caLabel_45->setObjectName(QString::fromUtf8("caLabel_45"));
        caLabel_45->setFrameShape(QFrame::NoFrame);
        caLabel_45->setForeground(QColor(251, 243, 74, 255));
        caLabel_45->setBackground(QColor(251, 243, 74, 0));
        caLabel_45->setVisibility(caLabel::IfNotZero);
        caLabel_45->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_45->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_45->setGeometry(QRect(83, 147, 204, 13));
        caTextEntry_20 = new caTextEntry(centralWidget);
        caTextEntry_20->setObjectName(QString::fromUtf8("caTextEntry_20"));
        caTextEntry_20->setGeometry(QRect(140, 265, 100, 25));
        caTextEntry_20->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_20->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_20->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_20->setLimitsMode(caLineEdit::Channel);
        caTextEntry_20->setLimitsMode(caLineEdit::Channel);
        caTextEntry_20->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_20->setMinValue(0);
        caTextEntry_20->setMaxValue(1);
        caTextEntry_20->setColorMode(caLineEdit::Static);
        caTextEntry_20->setFormatType(caTextEntry::decimal);
        caLabel_46 = new caLabel(centralWidget);
        caLabel_46->setObjectName(QString::fromUtf8("caLabel_46"));
        caLabel_46->setFrameShape(QFrame::NoFrame);
        caLabel_46->setForeground(QColor(0, 0, 0, 255));
        caLabel_46->setBackground(QColor(0, 0, 0, 0));
        caLabel_46->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_46->setGeometry(QRect(2, 268, 107, 18));
        caLabel_46->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_21 = new caTextEntry(centralWidget);
        caTextEntry_21->setObjectName(QString::fromUtf8("caTextEntry_21"));
        caTextEntry_21->setGeometry(QRect(335, 96, 100, 25));
        caTextEntry_21->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_21->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_21->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_21->setLimitsMode(caLineEdit::Channel);
        caTextEntry_21->setLimitsMode(caLineEdit::Channel);
        caTextEntry_21->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_21->setMinValue(0);
        caTextEntry_21->setMaxValue(1);
        caTextEntry_21->setColorMode(caLineEdit::Static);
        caTextEntry_21->setFormatType(caTextEntry::decimal);
        caLineEdit_12 = new caLineEdit(centralWidget);
        caLineEdit_12->setObjectName(QString::fromUtf8("caLineEdit_12"));
        caLineEdit_12->setGeometry(QRect(333, 560, 100, 18));
        caLineEdit_12->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_12->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_12->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_12->setLimitsMode(caLineEdit::Channel);
        caLineEdit_12->setLimitsMode(caLineEdit::Channel);
        caLineEdit_12->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_12->setMinValue(0);
        caLineEdit_12->setMaxValue(1);
        caLineEdit_12->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_12->setFormatType(caLineEdit::decimal);
        caLineEdit_12->setColorMode(caLineEdit::Static);
        caLabel_47 = new caLabel(centralWidget);
        caLabel_47->setObjectName(QString::fromUtf8("caLabel_47"));
        caLabel_47->setFrameShape(QFrame::NoFrame);
        caLabel_47->setForeground(QColor(0, 0, 0, 255));
        caLabel_47->setBackground(QColor(0, 0, 0, 0));
        caLabel_47->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_47->setGeometry(QRect(254, 560, 75, 18));
        caLabel_47->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_22 = new caTextEntry(centralWidget);
        caTextEntry_22->setObjectName(QString::fromUtf8("caTextEntry_22"));
        caTextEntry_22->setGeometry(QRect(0, 0, 150, 25));
        caTextEntry_22->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_22->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_22->setBackground(QColor(200, 200, 200, 255));
        caTextEntry_22->setLimitsMode(caLineEdit::Channel);
        caTextEntry_22->setLimitsMode(caLineEdit::Channel);
        caTextEntry_22->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_22->setMinValue(0);
        caTextEntry_22->setMaxValue(1);
        caTextEntry_22->setColorMode(caLineEdit::Static);
        caTextEntry_22->setFormatType(caTextEntry::decimal);
        caFrame_2 = new caFrame(centralWidget);
        caFrame_2->setObjectName(QString::fromUtf8("caFrame_2"));
        caFrame_2->setGeometry(QRect(254, 600, 181, 27));
        caTextEntry_23 = new caTextEntry(caFrame_2);
        caTextEntry_23->setObjectName(QString::fromUtf8("caTextEntry_23"));
        caTextEntry_23->setGeometry(QRect(79, 0, 100, 25));
        caTextEntry_23->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_23->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_23->setBackground(QColor(115, 223, 255, 255));
        caTextEntry_23->setLimitsMode(caLineEdit::Channel);
        caTextEntry_23->setLimitsMode(caLineEdit::Channel);
        caTextEntry_23->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_23->setMinValue(0);
        caTextEntry_23->setMaxValue(1);
        caTextEntry_23->setColorMode(caLineEdit::Static);
        caTextEntry_23->setFormatType(caTextEntry::decimal);
        caLabel_48 = new caLabel(caFrame_2);
        caLabel_48->setObjectName(QString::fromUtf8("caLabel_48"));
        caLabel_48->setFrameShape(QFrame::NoFrame);
        caLabel_48->setForeground(QColor(0, 0, 0, 255));
        caLabel_48->setBackground(QColor(0, 0, 0, 0));
        caLabel_48->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_48->setGeometry(QRect(0, 3, 99, 18));
        caLabel_48->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caTextEntry_24 = new caTextEntry(centralWidget);
        caTextEntry_24->setObjectName(QString::fromUtf8("caTextEntry_24"));
        caTextEntry_24->setGeometry(QRect(345, 0, 90, 20));
        caTextEntry_24->setFontScaleMode(caLineEdit::WidthAndHeight);
        caTextEntry_24->setForeground(QColor(0, 0, 0, 255));
        caTextEntry_24->setBackground(QColor(200, 200, 200, 255));
        caTextEntry_24->setLimitsMode(caLineEdit::Channel);
        caTextEntry_24->setLimitsMode(caLineEdit::Channel);
        caTextEntry_24->setPrecisionMode(caLineEdit::Channel);
        caTextEntry_24->setMinValue(0);
        caTextEntry_24->setMaxValue(1);
        caTextEntry_24->setColorMode(caLineEdit::Static);
        caTextEntry_24->setFormatType(caTextEntry::decimal);
        caFrame_3 = new caFrame(centralWidget);
        caFrame_3->setObjectName(QString::fromUtf8("caFrame_3"));
        caFrame_3->setGeometry(QRect(79, 69, 212, 24));
        caRectangle_3 = new caGraphics(caFrame_3);
        caRectangle_3->setObjectName(QString::fromUtf8("caRectangle_3"));
        caRectangle_3->setForm(caGraphics::Rectangle);
        caRectangle_3->setGeometry(QRect(2, 2, 206, 18));
        caRectangle_3->setLineSize(2);
        caRectangle_3->setForeground(QColor(251, 243, 74, 255));
        caRectangle_3->setBackground(QColor(251, 243, 74, 0));
        caRectangle_3->setLineColor(QColor(251, 243, 74, 255));
        caRectangle_3->setLinestyle(caGraphics::Solid);
        caRectangle_3->setVisibility(caGraphics::IfNotZero);
        caRectangle_4 = new caGraphics(caFrame_3);
        caRectangle_4->setObjectName(QString::fromUtf8("caRectangle_4"));
        caRectangle_4->setForm(caGraphics::Rectangle);
        caRectangle_4->setGeometry(QRect(0, 0, 210, 22));
        caRectangle_4->setLineSize(2);
        caRectangle_4->setForeground(QColor(0, 0, 0, 255));
        caRectangle_4->setBackground(QColor(0, 0, 0, 0));
        caRectangle_4->setLineColor(QColor(0, 0, 0, 255));
        caRectangle_4->setLinestyle(caGraphics::Solid);
        caRectangle_4->setVisibility(caGraphics::IfNotZero);
        caLabel_49 = new caLabel(centralWidget);
        caLabel_49->setObjectName(QString::fromUtf8("caLabel_49"));
        caLabel_49->setFrameShape(QFrame::NoFrame);
        caLabel_49->setForeground(QColor(251, 243, 74, 255));
        caLabel_49->setBackground(QColor(251, 243, 74, 0));
        caLabel_49->setVisibility(caLabel::IfNotZero);
        caLabel_49->setFontScaleMode(ESimpleLabel::WidthAndHeight);
        caLabel_49->setAlignment(Qt::AlignAbsolute|Qt::AlignHCenter|Qt::AlignVCenter);
        caLabel_49->setGeometry(QRect(60, 85, 23, 13));
        caLineEdit_13 = new caLineEdit(centralWidget);
        caLineEdit_13->setObjectName(QString::fromUtf8("caLineEdit_13"));
        caLineEdit_13->setGeometry(QRect(333, 580, 100, 18));
        caLineEdit_13->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_13->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_13->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_13->setLimitsMode(caLineEdit::Channel);
        caLineEdit_13->setLimitsMode(caLineEdit::Channel);
        caLineEdit_13->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_13->setMinValue(0);
        caLineEdit_13->setMaxValue(1);
        caLineEdit_13->setAlignment(Qt::AlignAbsolute|Qt::AlignLeft|Qt::AlignVCenter);
        caLineEdit_13->setFormatType(caLineEdit::decimal);
        caLineEdit_13->setColorMode(caLineEdit::Static);
        caMenu_0 = new caMenu(centralWidget);
        caMenu_0->setObjectName(QString::fromUtf8("caMenu_0"));
        caMenu_0->setGeometry(QRect(336, 324, 100, 18));
        caMenu_0->setForeground(QColor(0, 0, 0, 255));
        caMenu_0->setBackground(QColor(115, 223, 255, 255));
        caMenu_0->setColorMode(caMenu::Static);
        caLineEdit_14 = new caLineEdit(centralWidget);
        caLineEdit_14->setObjectName(QString::fromUtf8("caLineEdit_14"));
        caLineEdit_14->setGeometry(QRect(329, 229, 100, 18));
        caLineEdit_14->setFontScaleMode(caLineEdit::WidthAndHeight);
        caLineEdit_14->setForeground(QColor(10, 0, 184, 255));
        caLineEdit_14->setBackground(QColor(200, 200, 200, 255));
        caLineEdit_14->setAlignment(Qt::AlignAbsolute|Qt::AlignRight|Qt::AlignVCenter);
        caLineEdit_14->setLimitsMode(caLineEdit::Channel);
        caLineEdit_14->setLimitsMode(caLineEdit::Channel);
        caLineEdit_14->setPrecisionMode(caLineEdit::Channel);
        caLineEdit_14->setMinValue(0);
        caLineEdit_14->setMaxValue(1);
        caLineEdit_14->setFormatType(caLineEdit::decimal);
        caLineEdit_14->setColorMode(caLineEdit::Static);
        MainWindow->setCentralWidget(centralWidget);
        caLabel_0->raise();
        caLabel_1->raise();
        caLabel_2->raise();
        caLabel_3->raise();
        caLabel_4->raise();
        caLabel_5->raise();
        caLabel_6->raise();
        caRectangle_0->raise();
        caRectangle_1->raise();
        caLabel_7->raise();
        caLabel_8->raise();
        caLabel_9->raise();
        caLabel_10->raise();
        caFrame_0->raise();
        caLabel_11->raise();
        caLabel_12->raise();
        caLabel_13->raise();
        caLabel_14->raise();
        caLabel_15->raise();
        caLabel_16->raise();
        caLabel_17->raise();
        caLabel_18->raise();
        caLabel_19->raise();
        caLabel_20->raise();
        caLabel_21->raise();
        caLabel_22->raise();
        caLabel_23->raise();
        caLabel_24->raise();
        caLabel_25->raise();
        caLabel_26->raise();
        caLabel_27->raise();
        caLabel_28->raise();
        caLabel_29->raise();
        caLabel_30->raise();
        caLabel_31->raise();
        caLabel_32->raise();
        caLabel_33->raise();
        caLabel_34->raise();
        caLabel_35->raise();
        caLabel_36->raise();
        caLabel_37->raise();
        caLabel_38->raise();
        caLabel_39->raise();
        caLabel_40->raise();
        caLabel_41->raise();
        caLabel_42->raise();
        caFrame_1->raise();
        caGraphics_0->raise();
        caGraphics_1->raise();
        caLabel_43->raise();
        caLabel_44->raise();
        caRectangle_2->raise();
        caLabel_45->raise();
        caLabel_46->raise();
        caLabel_47->raise();
        caLabel_48->raise();
        caFrame_2->raise();
        caRectangle_3->raise();
        caRectangle_4->raise();
        caFrame_3->raise();
        caLabel_49->raise();
        caMessageButton_0->raise();
        caMessageButton_1->raise();
        caTextEntry_0->raise();
        caMessageButton_2->raise();
        caMessageButton_3->raise();
        caTextEntry_1->raise();
        caMessageButton_4->raise();
        caMessageButton_5->raise();
        caChoice_0->raise();
        caTextEntry_2->raise();
        caChoice_1->raise();
        caTextEntry_3->raise();
        caTextEntry_4->raise();
        caTextEntry_5->raise();
        caTextEntry_6->raise();
        caTextEntry_7->raise();
        caTextEntry_8->raise();
        caTextEntry_9->raise();
        caTextEntry_10->raise();
        caTextEntry_11->raise();
        caLineEdit_0->raise();
        caLineEdit_1->raise();
        caLineEdit_2->raise();
        caLineEdit_3->raise();
        caLineEdit_4->raise();
        caLineEdit_5->raise();
        caLineEdit_6->raise();
        caLineEdit_7->raise();
        caLineEdit_8->raise();
        caChoice_2->raise();
        caChoice_3->raise();
        caTextEntry_12->raise();
        caChoice_4->raise();
        caChoice_5->raise();
        caLineEdit_9->raise();
        caLineEdit_10->raise();
        caLineEdit_11->raise();
        caTextEntry_13->raise();
        caTextEntry_14->raise();
        caTextEntry_15->raise();
        caTextEntry_16->raise();
        caTextEntry_17->raise();
        caTextEntry_18->raise();
        caTextEntry_19->raise();
        caChoice_6->raise();
        caTextEntry_20->raise();
        caTextEntry_21->raise();
        caLineEdit_12->raise();
        caTextEntry_22->raise();
        caTextEntry_23->raise();
        caTextEntry_24->raise();
        caLineEdit_13->raise();
        caMenu_0->raise();
        caLineEdit_14->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setStyleSheet(QApplication::translate("MainWindow", "\n"
"\n"
"QWidget#centralWidget {background: rgba(200, 200, 200, 255);}\n"
"\n"
"caTable {\n"
"       font: 10pt;\n"
"       background: cornsilk;\n"
"       alternate-background-color: wheat;\n"
"}\n"
"\n"
"caLineEdit {\n"
"     border-radius: 1px;\n"
"     background: lightyellow;\n"
"     color: black;\n"
" }\n"
"\n"
"caTextEntry {\n"
"    color: rgb(127, 0, 63);\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c;\n"
"    selection-background-color: wheat;\n"
"    border: 1px groove black;\n"
"    border-radius: 1px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"caTextEntry:focus {\n"
"    padding: 0px;\n"
"    border: 2px groove darkred;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QPushButton {\n"
"      border-color: #00b;\n"
"      border-radius: 2px;\n"
"      padding: 3px;\n"
"      border-width: 1px;\n"
"\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"						   stop:0   rgba(224, 239, 255, 255),\n"
"						   stop:0.5 rgba(199, 215, 230, 255),\n"
"						   stop:1   rgba"
                        "(184, 214, 236, 255));\n"
"}\n"
"QPushButton:hover {\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"						stop:0   rgba(201, 226, 255, 255),\n"
"						stop:0.5 rgba(177, 204, 230, 255),\n"
"						stop:1   rgba(163, 205, 236, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"						stop:0   rgba(174, 219, 255, 255),\n"
"						stop:0.5 rgba(165, 199, 230, 255),\n"
"						stop:1   rgba(134, 188, 236, 255));\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1,\n"
"						stop:0   rgba(174, 219, 255, 255),\n"
"						stop:0.5 rgba(165, 199, 230, 255),\n"
"						stop:1   rgba(134, 188, 236, 255));\n"
"}\n"
"\n"
"caChoice {\n"
"      background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                  stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                  stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"caChoice > QPushButton {\n"
""
                        "      text-align: left;\n"
"      padding: 1px;\n"
"}\n"
"\n"
"caSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: lightgrey;\n"
"height: 20px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"caSlider::handle:horizontal {\n"
"background: red;\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"\n"
"", 0, QApplication::UnicodeUTF8));
        caLabel_0->setText(QApplication::translate("MainWindow", "(epics: claspcal_m1)", 0, QApplication::UnicodeUTF8));
        caLabel_1->setText(QApplication::translate("MainWindow", "Hi limit", 0, QApplication::UnicodeUTF8));
        caLabel_2->setText(QApplication::translate("MainWindow", "Readback", 0, QApplication::UnicodeUTF8));
        caLabel_3->setText(QApplication::translate("MainWindow", "Lo limit", 0, QApplication::UnicodeUTF8));
        caLabel_4->setText(QApplication::translate("MainWindow", "MoveAbs", 0, QApplication::UnicodeUTF8));
        caLabel_5->setText(QApplication::translate("MainWindow", "Tweak", 0, QApplication::UnicodeUTF8));
        caLabel_6->setText(QApplication::translate("MainWindow", "MoveRel", 0, QApplication::UnicodeUTF8));
        caRectangle_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HOMF", 0, QApplication::UnicodeUTF8));
        caRectangle_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HOMR", 0, QApplication::UnicodeUTF8));
        caMessageButton_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.TWF", 0, QApplication::UnicodeUTF8));
        caMessageButton_0->setLabel(QApplication::translate("MainWindow", ">", 0, QApplication::UnicodeUTF8));
        caMessageButton_0->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caMessageButton_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.TWR", 0, QApplication::UnicodeUTF8));
        caMessageButton_1->setLabel(QApplication::translate("MainWindow", "<", 0, QApplication::UnicodeUTF8));
        caMessageButton_1->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caTextEntry_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.TWV", 0, QApplication::UnicodeUTF8));
        caMessageButton_2->setChannel(QApplication::translate("MainWindow", "claspcal_m1.JOGR", 0, QApplication::UnicodeUTF8));
        caMessageButton_2->setLabel(QApplication::translate("MainWindow", "JogR", 0, QApplication::UnicodeUTF8));
        caMessageButton_2->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caMessageButton_2->setReleaseMessage(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        caMessageButton_3->setChannel(QApplication::translate("MainWindow", "claspcal_m1.JOGF", 0, QApplication::UnicodeUTF8));
        caMessageButton_3->setLabel(QApplication::translate("MainWindow", "JogF", 0, QApplication::UnicodeUTF8));
        caMessageButton_3->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caMessageButton_3->setReleaseMessage(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        caTextEntry_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RLV", 0, QApplication::UnicodeUTF8));
        caMessageButton_4->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HOMF", 0, QApplication::UnicodeUTF8));
        caMessageButton_4->setLabel(QApplication::translate("MainWindow", "HomF", 0, QApplication::UnicodeUTF8));
        caMessageButton_4->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caMessageButton_4->setReleaseMessage(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        caMessageButton_5->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HOMR", 0, QApplication::UnicodeUTF8));
        caMessageButton_5->setLabel(QApplication::translate("MainWindow", "HomR", 0, QApplication::UnicodeUTF8));
        caMessageButton_5->setPressMessage(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        caMessageButton_5->setReleaseMessage(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        caLabel_7->setText(QApplication::translate("MainWindow", "Off", 0, QApplication::UnicodeUTF8));
        caLabel_8->setText(QApplication::translate("MainWindow", "Cal", 0, QApplication::UnicodeUTF8));
        caLabel_9->setText(QApplication::translate("MainWindow", "Calibration", 0, QApplication::UnicodeUTF8));
        caChoice_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.SET", 0, QApplication::UnicodeUTF8));
        caTextEntry_2->setChannel(QApplication::translate("MainWindow", "claspcal_m1.OFF", 0, QApplication::UnicodeUTF8));
        caLabel_10->setText(QApplication::translate("MainWindow", "Dir", 0, QApplication::UnicodeUTF8));
        caChoice_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DIR", 0, QApplication::UnicodeUTF8));
        caTextEntry_3->setChannel(QApplication::translate("MainWindow", "claspcal_m1.BACC", 0, QApplication::UnicodeUTF8));
        caTextEntry_4->setChannel(QApplication::translate("MainWindow", "claspcal_m1.ACCL", 0, QApplication::UnicodeUTF8));
        caLabel_11->setText(QApplication::translate("MainWindow", "Accel.", 0, QApplication::UnicodeUTF8));
        caTextEntry_5->setChannel(QApplication::translate("MainWindow", "claspcal_m1.BDST", 0, QApplication::UnicodeUTF8));
        caLabel_12->setText(QApplication::translate("MainWindow", "Backlash distance", 0, QApplication::UnicodeUTF8));
        caTextEntry_6->setChannel(QApplication::translate("MainWindow", "claspcal_m1.FRAC", 0, QApplication::UnicodeUTF8));
        caLabel_13->setText(QApplication::translate("MainWindow", "Move Fraction", 0, QApplication::UnicodeUTF8));
        caLabel_14->setText(QApplication::translate("MainWindow", "User", 0, QApplication::UnicodeUTF8));
        caLabel_15->setText(QApplication::translate("MainWindow", "Dial", 0, QApplication::UnicodeUTF8));
        caTextEntry_7->setChannel(QApplication::translate("MainWindow", "claspcal_m1.VELO", 0, QApplication::UnicodeUTF8));
        caLabel_16->setText(QApplication::translate("MainWindow", "Speed", 0, QApplication::UnicodeUTF8));
        caLabel_17->setText(QApplication::translate("MainWindow", "Normal", 0, QApplication::UnicodeUTF8));
        caLabel_18->setText(QApplication::translate("MainWindow", "Backlash", 0, QApplication::UnicodeUTF8));
        caTextEntry_8->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MRES", 0, QApplication::UnicodeUTF8));
        caLabel_19->setText(QApplication::translate("MainWindow", "Motor res.", 0, QApplication::UnicodeUTF8));
        caTextEntry_9->setChannel(QApplication::translate("MainWindow", "claspcal_m1.ERES", 0, QApplication::UnicodeUTF8));
        caLabel_20->setText(QApplication::translate("MainWindow", "Encoder res.", 0, QApplication::UnicodeUTF8));
        caTextEntry_10->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RDBD", 0, QApplication::UnicodeUTF8));
        caLabel_21->setText(QApplication::translate("MainWindow", "Retry deadband", 0, QApplication::UnicodeUTF8));
        caTextEntry_11->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RTRY", 0, QApplication::UnicodeUTF8));
        caLabel_22->setText(QApplication::translate("MainWindow", "max:", 0, QApplication::UnicodeUTF8));
        caLineEdit_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RCNT", 0, QApplication::UnicodeUTF8));
        caLabel_23->setText(QApplication::translate("MainWindow", "Retries", 0, QApplication::UnicodeUTF8));
        caLabel_24->setText(QApplication::translate("MainWindow", "CurrDir", 0, QApplication::UnicodeUTF8));
        caLineEdit_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.TDIR", 0, QApplication::UnicodeUTF8));
        caLabel_25->setText(QApplication::translate("MainWindow", "Moving", 0, QApplication::UnicodeUTF8));
        caLineEdit_2->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MOVN", 0, QApplication::UnicodeUTF8));
        caLineEdit_3->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MSTA", 0, QApplication::UnicodeUTF8));
        caLabel_26->setText(QApplication::translate("MainWindow", "State  0x", 0, QApplication::UnicodeUTF8));
        caLabel_27->setText(QApplication::translate("MainWindow", "At Home", 0, QApplication::UnicodeUTF8));
        caLabel_28->setText(QApplication::translate("MainWindow", "Encoder", 0, QApplication::UnicodeUTF8));
        caLabel_29->setText(QApplication::translate("MainWindow", "MotorPos", 0, QApplication::UnicodeUTF8));
        caLabel_30->setText(QApplication::translate("MainWindow", "MIP    0x", 0, QApplication::UnicodeUTF8));
        caLineEdit_4->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DIFF", 0, QApplication::UnicodeUTF8));
        caLabel_31->setText(QApplication::translate("MainWindow", "Err", 0, QApplication::UnicodeUTF8));
        caLineEdit_5->setChannel(QApplication::translate("MainWindow", "claspcal_m1.ATHM", 0, QApplication::UnicodeUTF8));
        caLineEdit_6->setChannel(QApplication::translate("MainWindow", "claspcal_m1.REP", 0, QApplication::UnicodeUTF8));
        caLineEdit_7->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RMP", 0, QApplication::UnicodeUTF8));
        caLineEdit_8->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MIP", 0, QApplication::UnicodeUTF8));
        caLabel_32->setText(QApplication::translate("MainWindow", "Mode", 0, QApplication::UnicodeUTF8));
        caChoice_2->setChannel(QApplication::translate("MainWindow", "claspcal_m1.UEIP", 0, QApplication::UnicodeUTF8));
        caLabel_33->setText(QApplication::translate("MainWindow", "Use Encoder", 0, QApplication::UnicodeUTF8));
        caChoice_3->setChannel(QApplication::translate("MainWindow", "claspcal_m1.URIP", 0, QApplication::UnicodeUTF8));
        caLabel_34->setText(QApplication::translate("MainWindow", "Use Readback", 0, QApplication::UnicodeUTF8));
        caTextEntry_12->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RRES", 0, QApplication::UnicodeUTF8));
        caLabel_35->setText(QApplication::translate("MainWindow", "Readback res.", 0, QApplication::UnicodeUTF8));
        caLabel_36->setText(QApplication::translate("MainWindow", "VME Card#", 0, QApplication::UnicodeUTF8));
        caChoice_4->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MODE", 0, QApplication::UnicodeUTF8));
        caChoice_5->setChannel(QApplication::translate("MainWindow", "claspcal_m1.OMSL", 0, QApplication::UnicodeUTF8));
        caLabel_37->setText(QApplication::translate("MainWindow", "Dynamics", 0, QApplication::UnicodeUTF8));
        caLabel_38->setText(QApplication::translate("MainWindow", "Raw", 0, QApplication::UnicodeUTF8));
        caLabel_39->setText(QApplication::translate("MainWindow", "Lim", 0, QApplication::UnicodeUTF8));
        caLabel_40->setText(QApplication::translate("MainWindow", "Drive", 0, QApplication::UnicodeUTF8));
        caLabel_41->setChannel(QApplication::translate("MainWindow", "claspcal_m1.MOVN", 0, QApplication::UnicodeUTF8));
        caLabel_41->setText(QApplication::translate("MainWindow", "Moving", 0, QApplication::UnicodeUTF8));
        caLabel_42->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DMOV", 0, QApplication::UnicodeUTF8));
        caLabel_42->setText(QApplication::translate("MainWindow", "Done", 0, QApplication::UnicodeUTF8));
        caLineEdit_9->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RBV", 0, QApplication::UnicodeUTF8));
        caLineEdit_10->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DRBV", 0, QApplication::UnicodeUTF8));
        caLineEdit_11->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RRBV", 0, QApplication::UnicodeUTF8));
        caTextEntry_13->setChannel(QApplication::translate("MainWindow", "claspcal_m1.VAL", 0, QApplication::UnicodeUTF8));
        caTextEntry_14->setChannel(QApplication::translate("MainWindow", "claspcal_m1.LLM", 0, QApplication::UnicodeUTF8));
        caTextEntry_15->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DHLM", 0, QApplication::UnicodeUTF8));
        caTextEntry_16->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HLM", 0, QApplication::UnicodeUTF8));
        caTextEntry_17->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DVAL", 0, QApplication::UnicodeUTF8));
        caTextEntry_18->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DLLM", 0, QApplication::UnicodeUTF8));
        caTextEntry_19->setChannel(QApplication::translate("MainWindow", "claspcal_m1.BVEL", 0, QApplication::UnicodeUTF8));
        caChoice_6->setChannel(QApplication::translate("MainWindow", "claspcal_m1.SPMG", 0, QApplication::UnicodeUTF8));
        caGraphics_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.HLS", 0, QApplication::UnicodeUTF8));
        caGraphics_1->setChannel(QApplication::translate("MainWindow", "claspcal_m1.LLS", 0, QApplication::UnicodeUTF8));
        caLabel_43->setText(QApplication::translate("MainWindow", "Setup", 0, QApplication::UnicodeUTF8));
        caLabel_44->setText(QApplication::translate("MainWindow", "Status", 0, QApplication::UnicodeUTF8));
        caRectangle_2->setChannel(QApplication::translate("MainWindow", "claspcal_m1.LVIO", 0, QApplication::UnicodeUTF8));
        caLabel_45->setChannel(QApplication::translate("MainWindow", "claspcal_m1.LVIO", 0, QApplication::UnicodeUTF8));
        caLabel_45->setText(QApplication::translate("MainWindow", "Soft-Limit Violation", 0, QApplication::UnicodeUTF8));
        caTextEntry_20->setChannel(QApplication::translate("MainWindow", "claspcal_m1.VBAS", 0, QApplication::UnicodeUTF8));
        caLabel_46->setText(QApplication::translate("MainWindow", "Base Speed", 0, QApplication::UnicodeUTF8));
        caTextEntry_21->setChannel(QApplication::translate("MainWindow", "claspcal_m1.RVAL", 0, QApplication::UnicodeUTF8));
        caLineEdit_12->setChannel(QApplication::translate("MainWindow", "claspcal_m1.VERS", 0, QApplication::UnicodeUTF8));
        caLabel_47->setText(QApplication::translate("MainWindow", "Version", 0, QApplication::UnicodeUTF8));
        caTextEntry_22->setChannel(QApplication::translate("MainWindow", "claspcal_m1.DESC", 0, QApplication::UnicodeUTF8));
        caTextEntry_23->setChannel(QApplication::translate("MainWindow", "claspcal_m1.PREC", 0, QApplication::UnicodeUTF8));
        caLabel_48->setText(QApplication::translate("MainWindow", "Precision", 0, QApplication::UnicodeUTF8));
        caTextEntry_24->setChannel(QApplication::translate("MainWindow", "claspcal_m1.EGU", 0, QApplication::UnicodeUTF8));
        caRectangle_3->setChannel(QApplication::translate("MainWindow", "claspcal_m1.SET", 0, QApplication::UnicodeUTF8));
        caRectangle_4->setChannel(QApplication::translate("MainWindow", "claspcal_m1.SET", 0, QApplication::UnicodeUTF8));
        caLabel_49->setChannel(QApplication::translate("MainWindow", "claspcal_m1.SET", 0, QApplication::UnicodeUTF8));
        caLabel_49->setText(QApplication::translate("MainWindow", "SET", 0, QApplication::UnicodeUTF8));
        caLineEdit_13->setChannel(QApplication::translate("MainWindow", "claspcal_m1.CARD", 0, QApplication::UnicodeUTF8));
        caMenu_0->setChannel(QApplication::translate("MainWindow", "claspcal_m1.FOFF", 0, QApplication::UnicodeUTF8));
        caLineEdit_14->setChannel(QApplication::translate("MainWindow", "claspcal_m1_missed_steps", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MOTOR_EXPERT_H
