#!/bin/tcsh -f
#
#  adcecal1_start - starts DAQ to test VXS crates in Hall
#
#  SP, 04-Mar-2012


if ($HOST != adcecal1 && $HOST != adcecal1.jlab.org) then
  echo ""
  echo " You should be logged into adcecal1"
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_adcecal1"
set EB_t  = "-T EB_adcecal1"
set ER_t  = "-T ER_adcecal1"
set RC_t  = "-T runcontrol_adcecal1"
set XT1_t = "-T CRATE_adcecal1"
set XT2_t = "-T CRATE_tdcecal1"

set ET   = daq_comp_nossh.tcl
set EB   = daq_comp_nossh.tcl
set ER   = daq_comp_nossh.tcl
set RC   = daq_comp_nossh.tcl
set XT   = daq_comp_nossh.tcl

set ET_comp  = 'et_start -n 2000 -s 500000 -f /tmp/et_sys_clasprod'
set EB_comp  = 'coda_ebc -s clasprod -o "EB1 CDEB" '
set ER_comp  = 'coda_erc -s clasprod -o "ER1 ER" '
set RC_comp  = 'runcontrol -s clasprod -cedit -dbedit'
set XT1_comp = 'coda_roc_gef -s clasprod -o "adcecal1 ROC" '
set XT2_comp = 'rlogin tdcecal1'


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_adcecal1"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

echo " Start connection to CRATE_tdcecal1"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT2_comp >& /dev/null &`


echo ""
echo " adcecal1_start done"
echo ""


exit
