#!/usr/bin/perl

#  alarm_checker

#  makes alarm_checker info_server entry
# sends the number of alarms into timeline system

#  ejw, 11-feb-00


use Env;


#  Perl code
#-----------


#  decode command line args
$debug  = 0;
$line = join(" ",@ARGV);
($debug      =  1) if ($line =~ s/-debug\s*//i);


#  get alarm count
chomp($count=`java clonjava/alarm_mgr -count`);


#  form command
$cmd = "ipc_msg -a clasprod -dest info_server/in/alarm_checker"
    . " -type info_server -sender alarm_checker"
    . " -str alarm_checker -i4 $count";


#  execute command
if($debug==0) {
    system($cmd);
} else {
    print "\n$cmd\n\n";
}


#  done
exit;

