#!/bin/csh

#  ejw, 24-sep-01


if ($1 == start) then

  ssh -n $CLON_DAQ "(ipc2timeline -a $2) >>& $CLON_LOG/run_log/ipc2timeline.log &" &

else if ($1 == stop) then

  stop_ipc_proc -a $2 -i ipc2timeline -n $CLON_DAQ -p ipc2timeline >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
