#!/bin/csh

#  ejw, 24-sep-01


if ($1 == start) then

  set x=`ssh $CLON_DAQ "ps -e -o args | grep cmlogServer | grep -v control_cmlogServer | grep -vc grep"`
  if ($x < 1) then
    ssh -n $CLON_DAQ "$CMLOGROOT/bin/solaris/cmlogServer /usr/clas/cmlog/cmlog.config >>& /usr/clas/cmlog/cmlog.log &" &
  endif

else if ($1 == stop) then

  $CLON_BIN/stop_proc -n $CLON_DAQ -p cmlogServer >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
