#!/bin/csh

#  download_pretrig

#  called by download_trig_config to download pretrig thresholds

#  $1 is system type (cc,ec,sc,etc)
#  $2 is full pretrig file name

#  ejw, 7-nov-2001


rm -f $CLON_PARMS/pretrigger/conf/l1_$1.conf
ln -s $2 $CLON_PARMS/pretrigger/conf/l1_$1.conf 
$CODA_BIN/dimanc set p $1


