#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#  get info of JLAB VME Discriminators DSC2
#
#  functions:
#             dsc2MonAll   ()
#             dsc2MonBoard (int board_number)
#
#  SP, 24-Apr-2012


set inp_str [split $argv " "]
set inp_N   [llength $inp_str]
set roc     -1
set tmp1    -1


#***  Check input parameters ***
set flag 0
if { ($inp_N < 1) || ($inp_N > 2) } {               set flag 1
} else {
  set roc     [string tolower [lindex $inp_str 0]]
  if { $inp_N == 2 } {
    set tmp1  [string tolower [lindex $inp_str 1]]
    if { ($tmp1 < 1) || ($tmp1 > 40) } {            set flag 2
    } elseif { [string match "*\[a-z\]*" $tmp1] } { set flag 3
    }
  }
}
#puts "\n flag=$flag; \n inp_N=$inp_N; \n roc=$roc; \n tmp1=$tmp1;"


#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: dsc2_mon  roc  \[D\]"
 puts "        ------------------"
 puts " Where \"roc\" - name of VME crate"
 puts "         \"D\" - Discriminator_Number from left to right"
 puts "               could be skipped (default=\"all\")\n"
 exit
}


#***  Execute function ***
if { $inp_N == 1 } {
  set exename "dsc2MonAll()"
} else {
  set Dn [expr $tmp1 - 1]
  set exename "dsc2MonBoard($Dn)"
}

set result " error: Can't get result for $exename \n"
catch {set result [exec tcpClient $roc $exename]}
puts "\n$result"

exit
