#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#  Remote start of Phillips generator 7120 (dt2=ddt=0).
#    (using Tick timer3 on the MCChip, Memory controller)
#
#    function:  gen7120_start (c, n, dt1, dt2, ddt, rate, N)
#
#    function inputs:
#        c - CAMAC Crate Controller number;
#        n - CAMAC slot number, position of gen7120;
#      dt1 - Start-to-Stop delay (0-10000 nSec);
#     rate - frequency of generated Start-Stop signals;
#        N - number of Start/Stop pairs.
#
#  SP, 07-Oct-2002


set roc  "camac1"
set c     2
set n    18
set dt    0
set dt2   0
set ddt   0
set rate  0
set N     0

set rocs    " camac1 croctest4 "
set inp_str [split $argv " "]
set inp_N   [llength $inp_str]


#***  Check input parameters ***
set flag 0
if { ($inp_N < 3) || ($inp_N > 6) } { set flag 1
} else {
  set dt   [lindex $inp_str 0]
  set rate [lindex $inp_str 1]
  set N    [lindex $inp_str 2]
  if { $inp_N > 3 } { set roc [string tolower [lindex $inp_str 3]] }
  if { $inp_N > 4 } { set c   [lindex $inp_str 4] }
  if { $inp_N > 5 } { set n   [lindex $inp_str 5] }
  if       {    ($dt < 0) || ($dt   > 10000)  } { set flag 2
  } elseif {  ($rate < 1) || ($rate > 10000)  } { set flag 3
  } elseif {     ($N < 1) && ($N   != -1)     } { set flag 4
  } elseif { ![string match "* $roc *" $rocs] } { set flag 5
  } elseif {     ($c < 0) || ($c    > 7)      } { set flag 6
  } elseif {     ($n < 1) || ($n    > 24)     } { set flag 7
  }
}
#puts "\n   flag=$flag;\n   inp_str=$inp_str;\n   inp_N=$inp_N;"
#puts " dt=$dt,\n rate=$rate,\n N=$N,\n roc=$roc,\n c=$c,\n n=$n.\n"


#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: gen7120_start dt rate N \[roc\] \[c\] \[n\]"
 puts "        -------------------------------------"
 puts " Where  \"dt\" - Start-to-Stop delay (0-10000 nSec);"
 puts "      \"rate\" - frequency of Start/Stop signals (1-10000 Hz);"
 puts "         \"N\" - number of Start/Stop pairs (N>1),"
 puts "               mode of continuous generation can be set, put N=-1;"
 puts "       \"roc\" - ROC name from the list \"camac1 croctest4\","
 puts "               could be skipped (default=\"camac1\");"
 puts "         \"c\" - CAMAC Crate Controller number, (default=2);"
 puts "         \"n\" - CAMAC slot number, position of gen7120, (default=18).\n"
 exit
}


set result "\n error: Can't get result for gen7120_start() \n"
catch {set result [exec tcpClient $roc gen7120_start($c,$n,$dt,$dt2,$ddt,$rate,$N)]}
puts "$result"


exit
