#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#  Remote get state of Phillips generator 7120.
#    (lib uses Tick timer3 on the MCChip, Memory controller)
#
#    function:  gen7120_stat (c, n, prn)
#
#    function inputs:
#        c - CAMAC Crate Controller number;
#        n - CAMAC slot number, position of gen7120;
#      prn - print flag (Short, Full, Long).
#
#  SP, 07-Oct-2002


set roc  "camac1"
set c     2
set n    18
set prn   0

set rocs    " camac1 croctest4 "
set inp_str [split $argv " "]
set inp_N   [llength $inp_str]


#***  Check input parameters ***
set flag 0
if { $inp_N > 4 } { set flag 1
} else {
  if { $inp_N > 0 } {
    set tmp  [string tolower [lindex $inp_str 0]]
    if { [string match "* $tmp *" $rocs] } {
      set roc $tmp
      if { $inp_N > 1 } { set c   [lindex $inp_str 1] }
      if { $inp_N > 2 } { set n   [lindex $inp_str 2] }
    } else {
      set prn  [lindex $inp_str 0]
      if { $inp_N > 1 } { set roc [string tolower [lindex $inp_str 1]] }
      if { $inp_N > 2 } { set c   [lindex $inp_str 2] }
      if { $inp_N > 3 } { set n   [lindex $inp_str 3] }
    }
  }
  if       {   ($prn < 0) || ($prn  > 2)      } { set flag 2
  } elseif { ![string match "* $roc *" $rocs] } { set flag 3
  } elseif {     ($c < 0) || ($c    > 7)      } { set flag 4
  } elseif {     ($n < 1) || ($n    > 24)     } { set flag 5
  }
}
#puts "\n   flag=$flag;\n   inp_str=$inp_str;\n   inp_N=$inp_N;"
#puts " prn=$prn,\n roc=$roc,\n c=$c,\n n=$n.\n"


#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: gen7120_stat \[prn\] \[roc\] \[c\] \[n\]"
 puts "        --------------------------------"
 puts " Where \"prn\" - print flag, could be skipped (default=0),"
 puts "               0 = print Short Status, 1 = Full, 2 = Long;"
 puts "       \"roc\" - ROC name from the list \"camac1 croctest4\","
 puts "               could be skipped (default=\"camac1\");"
 puts "         \"c\" - CAMAC Crate Controller number, (default=2);"
 puts "         \"n\" - CAMAC slot number, position of gen7120, (default=18).\n"
 exit
}


set result "\n error: Can't get result for gen7120_stat() \n"
catch {set result [exec tcpClient $roc gen7120_stat($c,$n,$prn)]}
puts "$result"


exit
