#!/bin/tcsh -f
#
#  hps_start - starts DAQ for HPS testsetup (Counting Room)
#
#  SP, 24-Feb-2012
#  SP, 01-Mar-2012  :  implement daq_comp.tcl


if ($HOST != clonusr3.jlab.org) then
  echo ""
  echo " You should be logged into clonusr3."
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_hps"
set EB_t  = "-T EB_hps"
set ER_t  = "-T ER_hps"
set RC_t  = "-T runcontrol_hps"
set XT1_t = "-T CRATE_hps1"
set XT2_t = "-T CRATE_hps2"
set XT3_t = "-T CRATE_hpstracker"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 2000 -s 500000 -f /tmp/et_sys_clashps'
set EB_comp  = 'coda_ebc -s clashps -o "EB9 CDEB" -i'
set ER_comp  = 'coda_erc -s clashps -o "ER9 ER" -i'
set RC_comp  = 'runcontrol -s clashps -cedit -dbedit'
set XT1_comp  = 'coda_roc_gef -s clashps -o "hps1 ROC" -i '
set XT2_comp  = 'coda_roc_gef -s clashps -o "hps2 ROC" -i '
set XT3_comp  = 'coda_roc -s clashps -o "hpstracker ROC" -i '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_hps1"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

echo " Start connection to CRATE_hps2"
set ypos  = `expr $ypos + $yinc + 60`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT2_comp >& /dev/null &`

echo " Start connection to CRATE_hpstracker"
set ypos  = `expr $ypos + $yinc + 60`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT3_t $color $geom$ypos -e $XT $XT3_comp >& /dev/null &`

echo ""
echo " hps_start done"
echo ""


exit
