#!/bin/csh
#
# hpsmon_exit - stop all monitoring processes on clonusr4
#
echo "Stop et2et"
sleep 5
stop_proc -n clonusr3 -p et_2_et >& /dev/null

echo "Stop clas_et_start"
sleep 5
stop_proc -n clonusr4 -p et_start -match "clashpsmon" >& /dev/null

echo "Remove ET system file"
sleep 5
ssh -n clonusr4 "rm -f /tmp/et_sys_clashpsmon            >& /dev/null &" &

echo "hpsmon_exit done."
#
