#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
# init_level2
#   set TS level2 variable to 0

if { [llength $argv] != 0 } {
  set roc $argv
} else {
  set roc "clastrig2"
}

set err [catch {set status [exec tcpClient $roc reset_ts_level2]}]

if {$err!=0} {exit $err} else {exit 0}

