#!/bin/csh
#
# mon_exit - stop all monitoring processes on CLON_MON0
#

echo "Stop et2et_daq_mon0"
stop_proc -n $CLON_MON0 -p et_2_et -match "primex" -s 0

echo "Stop clas_et_start"
sleep 5
stop_proc -n $CLON_MON0 -p et_start -match "primex" -s 0

echo "Remove ET system file"
sleep 5
ssh -n $CLON_MON0 "rm -f /tmp/et_sys_primex >& /dev/null &" &

echo "mon0_exit done."
#
