#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#  Remote correct pulser stop,
#  "pulser" here means a COMBINED SET of two generators:
#   KineticSystem Programmable Clock Generator 3660
#   and Phillips Charge/Time Generator 7120.
#
#    function:  pulser_stop ()
#
#  SP, 07-Oct-2002


set roc     "camac1"
set rocs    " camac1 croctest4 "
set inp_str [split $argv " "]
set inp_N   [llength $inp_str]


#***  Check input parameters ***
set flag 0
if { $inp_N > 1 } { set flag 1
} else {
  if { $inp_N > 0 } { set roc [string tolower [lindex $inp_str 0]] }
  if { ![string match "* $roc *" $rocs] } { set flag 2
  }
}
#puts "\n flag=$flag;\n inp_str=$inp_str;\n inp_N=$inp_N,\n roc=$roc.\n"


#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: pulser_stop \[roc\]"
 puts "        -----------------"
 puts " Where \"roc\" - ROC name from the list \"camac1 croctest4\","
 puts "               could be skipped (default=\"camac1\").\n"
 exit $flag
}


set result "\n error: Can't get result for pulser_stop() \n"

catch {set result [exec tcpClient $roc pulser_stop()]}

puts "$result"


if       { [string match "*stopped.*" $result] } { exit  0
} elseif { [string match "*rror*" $result]     } { exit 30
} else   { exit 40
}
