#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#  Read back data from Random Pulser.
#
#    functions:  r_pulser_ReadPort (AB)
#                r_pulser_Read     ()
#
#       inputs:  AB - port chooser
#
#  SP, 04-Oct-2002


set roc    "camac1"
set AB     "AB"
set ab      3

set rocs    " camac1 croctest4 primexts2 "
set inp_str [split $argv " "]
set inp_N   [llength $inp_str]


#***  Check input parameters ***
set flag 0
if { $inp_N > 2 } { set flag 1
} else {
  if       { $inp_N == 1 } {
    set roc_x [string tolower [lindex $inp_str 0]]
    if { ![string match "* $roc_x *" $rocs] } {
      set AB  [string toupper [lindex $inp_str 0]]
    } else {
      set roc $roc_x
    }
  } elseif { $inp_N == 2 } {
    set AB  [string toupper [lindex $inp_str 0]]
    set roc [string tolower [lindex $inp_str 1]]
  }
  if       { $AB == "A"  } { set ab 1
  } elseif { $AB == "B"  } { set ab 2
  } elseif { $AB == "AB" } { set ab 3
  } else                   { set flag 2
  }
  if { ![string match "* $roc *" $rocs] } { set flag 3
  }
}
#puts "\n   flag=$flag;\n   inp_str=$inp_str;\n   inp_N=$inp_N;"
#puts " AB=$AB,\n ab=$ab,\n roc=$roc.\n"


#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: r_pulser_read \[A/B/AB\] \[roc\]"
 puts "        ----------------------------"
 puts " Where \"AB\" - port chooser:"
 puts "              A for Source-A (Port1), B for Source-B (Port2),"
 puts "              could be skipped (default=\"AB\", read both ports);"
 puts "      \"roc\" - ROC name from the list \"camac1 croctest4 primexts2\","
 puts "              could be skipped (default=\"camac1\").\n"
 exit $flag
}


if { ($ab != 1) && ($ab != 2) } {
  set result "\n error: Can't get result for r_pulser_Read() \n"
  catch {set result [exec tcpClient $roc r_pulser_Read()]}
  puts "\n$result\n"
} else {
  set result "\n error: Can't get result for r_pulser_ReadPort() \n"
  catch {set result [exec tcpClient $roc r_pulser_ReadPort($ab,1)]}
  puts "\n$result\n"
}


exit
