#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
#
# set TS prescale factors
#
#  05/26/1999 - written  by V. Gyurjyan
#  07/11/1999 - updated  by V. Gyurjyan
#  08/27/2010 - modified by SP: added croctest10 and primexts2


set roc_name " clastrig2 croctest10 primexts2 "
set p03      16777215
set p47      65535
set inp_str  [split $argv " "]
set inp_N    [llength $inp_str]
set flag     0


#***  Check input parameters and assign prescale bits ***
if { ($inp_N < 8) || ($inp_N > 9) }     { set flag 1
} else {
  set parm_0 [lindex $inp_str 0]
  if { [string match "* $parm_0 *" $roc_name] } {
    if { $inp_N == 8 }                  { set flag 2
    } else {
	    set roc $parm_0
	    set n0 1
    }
  } else {
    if { $inp_N == 9 }                  { set flag 3
    } else {
	    set roc "clastrig2"
	    set n0 0
    }
  }
}
if { $flag == 0 } {
  for {set i $n0} { $i<$inp_N } { incr i } {
    set pi  [lindex $inp_str $i]
    set idx [expr $i-$n0]
    if { (0 <= $idx) && ($idx <= 3) } {
      if { ($pi < 0) || ($pi > $p03) }  { set flag 4 }
      foreach pjj [split $pi ""] {
        if { ($pjj < 0) || ($pjj > 9) } { set flag 5 }
      }
    }
    if { (4 <= $idx) && ($idx <= 7) } {
      if { ($pi < 0) || ($pi > $p47) }  { set flag 6 }
      foreach pjj [split $pi ""] {
        if { ($pjj < 0) || ($pjj > 9) } { set flag 7 }
      }
    }
  }
}


#***  Print help message ***
if { $flag != 0 } {
  puts "\n Usage:  s_ts_prescale \[roc\] p1 p2 p3 p4 p5 p6 p7 p8"
  puts "         -------------------------------------------"
  puts " Where   \"pi\"  - prescale factors for first 8 TS trigger bits"
  puts "                 p1-p4 could be set in range from 0 to 16777215"
  puts "                 p5-p8 could be set in range from 0 to 65535"
  puts "                 *** NOTE: set 0 means prescale 1, set 1 - prescale 2, ..."
  puts "         \"roc\" - ROC name from the list"
  puts "                \"clastrig2 croctest10 primexts2\","
  puts "                 could be skipped (\"clastrig2\" by default).\n"
  exit $flag
}


#***  Set trigger bit code ***
set p1 [lindex $argv [expr 0+$n0]]
set p2 [lindex $argv [expr 1+$n0]]
set p3 [lindex $argv [expr 2+$n0]]
set p4 [lindex $argv [expr 3+$n0]]
set p5 [lindex $argv [expr 4+$n0]]
set p6 [lindex $argv [expr 5+$n0]]
set p7 [lindex $argv [expr 6+$n0]]
set p8 [lindex $argv [expr 7+$n0]]

set err [catch {set z [exec tcpClient $roc prescale_all($p1,$p2,$p3,$p4,$p5,$p6,$p7,$p8)]}]
if {$err!=0} {
  puts "\n Unable to set TS prescales for \"$roc\", err: $err \n"
  exit $err
} else {
  puts "\n For \"$roc\" setting following prescales: $p1 $p2 $p3 $p4 $p5 $p6 $p7 $p8 \n"
}


exit

