#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  set_ts_runlock

#   sets TS run lock

#   ejw, 20-apr-98


# set ts run_lock word
set status ""  

set err [catch {set status [exec tcpClient clastrig2 set_ts_runlock]}]

if {$err!=0} {
    puts "$status"
    puts "DP_ask error: $err"
}

exit $err
