#!/bin/csh -f
#
#  svt_exit - stops all processes for SVT testsetup
#
#  SP, 24-Feb-2012
#  SP, 16-Jan-2013  :  generic for svt1,2,3,4,5,6


set hh = `echo $HOST | cut -c 1-3 `
set nn = `echo $HOST | cut -c 4-4 `
set host_name  = "svt$nn"

if ($hh != "svt") then
  echo ""
  echo " You should be logged into svt machine"
  echo ""
  exit (1)
endif

echo ""
echo " Stop ROCs"
stop_proc -n $host_name -p coda_roc_gef -match "classvt" -s 0

echo ""
echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "classvt" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "classvt" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "classvt" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "classvt" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "classvt" -s 0
#kill -9 `ps -ef | grep et_start | grep et_sys_classvt | awk '{print $2}'`

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_classvt


set ET_t  = "ET_svt$nn"
set EB_t  = "EB_svt$nn"
set ER_t  = "ER_svt$nn"
set RC_t  = "runcontrol_svt$nn"
set XT1_t = "CRATE_svt$nn"

echo ""
echo " Kill terminals:"
stop_proc -n $host_name -p xterm -match "$ET_t" -s 0
echo "                 ET_svt$nn done"

stop_proc -n $host_name -p xterm -match "$EB_t" -s 0
echo "                 EB_svt$nn done"

stop_proc -n $host_name -p xterm -match "$ER_t" -s 0
echo "                 ER_svt$nn done"

stop_proc -n $host_name -p xterm -match "$RC_t" -s 0
echo "                 runcontrol_svt$nn done"

stop_proc -n $host_name -p xterm -match "$XT1_t" -s 0
echo "                 CRATE_svt$nn done"


echo ""
echo " svt_exit done"
echo ""


exit
