#!/bin/tcsh -f
#
#  test0_start - starts DAQ for CODA testing
#

set hh = `echo $HOST | cut -c 1-3 `

#if ($hh != test0") then
#  echo ""
#  echo " You should be logged into test0 machine"
#  echo ""
#  exit (1)
#endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_test0"
set EB_t  = "-T EB_test0"
set ER_t  = "-T ER_test0"
set RC_t  = "-T runcontrol_test0"
set XT1_t = "-T CRATE_test0"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp_nossh.tcl

set ET_comp   = 'et_start -n 1000 -s 100000 -f /tmp/et_sys_clastest0'
set EB_comp1  = 'coda_ebc -s clastest0 -o "EB0'
set EB_comp2  = ' CDEB" '
set EB_comp   = "$EB_comp1$EB_comp2"
set ER_comp1  = 'coda_erc -s clastest0 -o "ER0'
set ER_comp2  = ' ER" '
set ER_comp   = "$ER_comp1$ER_comp2"
set RC_comp   = 'runcontrol -s clastest0 -cedit -dbedit'
set XT1_comp1 = 'coda_roc -s clastest0 -o "ROC0'
set XT1_comp2 = ' ROC" '
set XT1_comp  = "$XT1_comp1$XT1_comp2"


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_test0"
###set roc   = "test0"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`


echo ""
echo " test0_start done"
echo ""


exit
