#!/bin/csh -f
#
#  test0_exit - stops all processes for CODA testing
#

set hh = `echo $HOST | cut -c 1-8 `
set host_name = $hh
if ($hh != "clonioc1") then
  echo ""
  echo " You should be logged into clonioc1 machine"
  echo ""
  exit (1)
endif


echo ""
echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "clastest0" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "clastest0" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "clastest0" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "clastest0" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "clastest0" -s 0

echo " Stop ROC"
stop_proc -n $host_name -p coda_roc -match "clastest0" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clastest0


set ET_t  = "ET_test0"
set EB_t  = "EB_test0"
set ER_t  = "ER_test0"
set RC_t  = "runcontrol_test0"
set XT1_t = "CRATE_test0"

echo ""
echo " Kill terminals:"
stop_proc -n $host_name -p xterm -match "$ET_t" -s 0
echo "                 ET_test0 done"

stop_proc -n $host_name -p xterm -match "$EB_t" -s 0
echo "                 EB_test0 done"

stop_proc -n $host_name -p xterm -match "$ER_t" -s 0
echo "                 ER_test0 done"

stop_proc -n $host_name -p xterm -match "$RC_t" -s 0
echo "                 runcontrol_test0 done"

stop_proc -n $host_name -p xterm -match "$XT1_t" -s 0
echo "                 CRATE_test0 done"


echo ""
echo " test0_exit done"
echo ""


exit
