#define SOCKET_CREATE_FAILED 1
#define GETHOSTBYNAME_FAILED 2
#define CONNECT_FAILED 3
#define SOCKET_WRITE_FAILED 4
#define SOCKET_READ_FAILED 5
#define MEM_TEST_ERROR 6
#define NETWORK_CHECKSUM_ERROR 7
