TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db

DB += HVCAENx527ch.db
DB += HVCAENx527chItLk.db
DB += HVCAENx527cr.db
DB += HVCAENx527.db
DB += DetCh.db
DB += DetChItLk.db
DB += readConfigGlobalMPOD.db
DB += readConfigChassisMPOD.db
DB += mpod_chassis.db
DB += readConfigBoardsMPOD.db
DB += mpv_8008l.db
DB += mpv_8030.db
DB += ehs_f_205pf.db
DB += ehs_f_201pf.db
DB += DetEhs_f_205pf.db
DB += DetEhs_f_201pf.db
DB += DetMpv_8008l.db
DB += DetMpv_8030l.db
DB += DetMpv_8030.db
DB += DetWF.db
DB += DetChItLk_FDC.db


DB += hybLV.db
DB += svtChanOnOff.db
DB += svtOnOff.db
DB += svtBiasSetpoints.db  

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

