#!/bin/bash
#
#
#

###ioc_cron_exec $1 st_mpod.cmd mstart "/usr/local/clas12/release/0.1/epics/apps/iocBoot/iocmpodCrates"
ioc_cron_exec $1 mpodCrates mstart "/usr/local/clas12/release/0.1/epics/apps/iocBoot/iocmpodCrates"
