#!/bin/bash




#echo $1
#source ~/.cshrc

#ls
#set val="/misc/clas/clas12/R3.14.12.3/epicsB/baseB/src/CAEN_HV/level0/IocShell"
#export DIM_DNS_NODE=clonpc3
###ioc_cron_exec $1 ioccaenold costart "/misc/clas/clas12/R3.14.12.3/epicsB/baseB/src/CAEN_HV/level0/iocShellOld" 
ioc_cron_exec $1 ioccaen cstart "/usr/local/clas12/release/0.1/epics/drivers/CAEN_HV/level0/IocShellOld"

#echo 1 > /home/sytnik/t1
#echo $DIM_DNS_NODE >> /home/sytnik/t1
#echo 2  >> /home/sytnik/t1
#echo $2  >> /home/sytnik/t1

#cstart
#source /home/sytnik/.cshrc
#export DIM_DNS_NODE=$2

#echo $DIM_DNS_NODE > /misc/home/sytnik/ioc_watchdog/t0.txt
# /misc/home/sytnik/ioc_watchdog/cstart
#/misc/home/sytnik/ioc_watchdog/t > /dev/null
#/misc/clas/clas12/R3.14.12.3/epicsB/baseB/src/CAEN_HV/level0/IocShell/cstart