#  makefile for dchv
#  vhg,ejw 4-oct-2000

SHELL = /bin/sh

all:
#	cd s;    $(MAKE) all
	@echo "Nothing to compile"
 
clean:
#	cd s;    $(MAKE) clean
	@echo "Nothing to clean"
 
distclean:
#	cd s;    $(MAKE) distclean
	@echo "Nothing to distclean"
 
install: exports
exports:
#	cd s;    $(MAKE) exports
	cd dchv; $(MAKE) install

