######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 25 13:51:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS = mytest.ui
HEADERS = mytest.h
SOURCES = main.cpp mytest.cpp
