#!/usr/bin/csh -f 

#vhg 03/08/00

#  check if display env var set
if ($?DISPLAY) then
else
    echo "" 
    echo "   Error...DISPLAY env variable not set"
    echo "" 
    exit(-1)
endif

#setenv DISPLAY clon03:0.2

#  set classpath
###setenv CLASSPATH /usr/local/clas/release/jar/jcchart362Jvc.jar:/usr/local/clas/release/jar/jctable362Jvc.jar:/usr/local/clas/release/jar/cls_v331_jdk11.jar:/usr/local/clas/release/jar/dbaw.zip:/usr/local/clas/release/jar/dbaw_awt.jar:/usr/local/clas/release/jar/klg.jar:/usr/local/clas/release/jar/databind.jar:/usr/local/clas/release/jar/symbeans.jar:/usr/local/clas/release/jar/symclass.zip:/usr/local/clas/release/jar/swingall.jar:/usr/local/clas/release/jar/BeanGenerator.jar:/usr/local/clas/release/jar/ss.jar:/usr/local/clas/release/jar/clon.jar:/usr/local/clas/jar/imaginary.jar:/usr/local/clas/jar/dplite.jar:/usr/local/clas/bin:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jh.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/swingall.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jas.jar:/usr/local/clas/release/jar/tlc.jar:

#setenv CLASSPATH /usr/local/clas/release/jar/tlc.jar:/usr/local/clas/release/jar/cls_v331_jdk11.jar:/usr/local/clas/release/jar/dbaw.zip:/usr/local/clas/release/jar/dbaw_awt.jar:/usr/local/clas/release/jar/klg.jar:/usr/local/clas/release/jar/databind.jar:/usr/local/clas/release/jar/symbeans.jar:/usr/local/clas/release/jar/symclass.zip:/usr/local/clas/release/jar/swingall.jar:/usr/local/clas/release/jar/BeanGenerator.jar:/usr/local/clas/release/jar/ss.jar:/usr/local/clas/release/jar/clon.jar:/usr/local/clas/jar/imaginary.jar:/usr/local/clas/jar/dplite.jar:/usr/local/clas/bin:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jh.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/swingall.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jas.jar 

#/apps/java/jdk1.1.7/bin/java DaqTlc > & /dev/null &
/apps/java/jdk1.1.7/bin/java Daqtlc 



