#!/usr/bin/csh -f 

#vhg 03/08/00

#  check if display env var set
if ($?DISPLAY) then
else
    echo "" 
    echo "   Error...DISPLAY env variable not set"
    echo "" 
    exit(-1)
endif
 
if ($HOST != "clon10") then
    echo ""
    echo " Daqtlc will not run on $HOST"
    echo " Please use clon10"
    echo ""
    exit(-1)
endif

#  set classpath

setenv CLASSPATH .:/usr/local/clas/release/current/bin:/usr/local/clas/release/current/jar/tlc.jar:/usr/local/clas/release/current/jar/clon.jar:/usr/local/clas/release/current/jar/dplite.jar:/usr/local/clas/release/current/jar/sa_tlc.jar:/usr/local/clas/release/current/jar/status_display.jar:/usr/local/clas/release/current/jar/AlarmBrowser.jar:/usr/local/clas/release/current/share/jar/cariboulake.jar:/usr/local/clas/release/current/share/jar/klg.jar:/usr/local/clas/release/current/share/jar/jas.jar:/usr/local/clas/release/current/share/jar/jcchart362Jvc.jar:/usr/local/clas/release/current/share/jar/jctable362Jvc.jar:/usr/local/clas/release/current/share/jar/jh.jar:/usr/local/clas/release/current/share/jar/mysql.jar:/usr/local/clas/release/current/share/jar/ss.jar:/usr/local/clas/release/current/share/jar/swingall.jar:/usr/local/clas/release/current/share/jar/symbeans.jar:/usr/local/clas/release/current/share/jar/imaginary.jar

#Ipc_eber 
#Ipc_roc 
#Ipc_ts 


#/apps/java/jdk1.1.7/bin/java Daqtlc > & /dev/null &
###/apps/java/jdk1.1.7/bin/java Daqtlc 
#java Daqtlc
/u/apps/java/j2sdk1.4.2_03/bin/java Daqtlc














