#!/usr/bin/csh -f 

#vhg 03/08/00

#  check if display env var set
if ($?DISPLAY) then
else
    echo "" 
    echo "   Error...DISPLAY env variable not set"
    echo "" 
    exit(-1)
endif

unsetenv JAVA_HOME

#  set classpath
###setenv CLASSPATH .:$CLON_JAR/tlc.jar:"$CLON_JAR"/jcchart362Jvc.jar:"$CLON_JAR"/jctable362Jvc.jar:"$CLON_JAR"/cls_v3_4_3_jdk11.jar:"$CLON_JAR"/dbaw.zip:"$CLON_JAR"/dbaw_awt.jar:"$CLON_JAR"/klg.jar:"$CLON_JAR"/databind.jar:"$CLON_JAR"/symbeans.jar:"$CLON_JAR"/symclass.zip:"$CLON_JAR"/swingall.jar:"$CLON_JAR"/BeanGenerator.jar:$CLON_JAR/ss.jar:$CLON_JAR/clon.jar:$CLON_JAR/imaginary.jar:$CLON_JAR/dplite.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jh.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/swingall.jar:/u/group/clon/jas/solaris/jas-2.0alpha2/lib/jas.jar




#/apps/java/jdk1.1.7/bin/java Daqtlc > & /dev/null &
/apps/java/jdk1.1.7/bin/java InfoDaqtlc &



