/* CoErrorDecode.idl -- CoErrorDecode IDL */

/* Copyright (c) 2001 Wind River Systems, Inc. */

/*

modification history
--------------------
01a,09aug01,nel  created

*/

/*

DESCRIPTION

This file implements the CoErrorDecode CoClass which has one interface
call IDecode. This contains methods for decoding an HRESULT into 
a string representation.

*/

#ifdef _WIN32
import "unknwn.idl";
#else
import "vxidl.idl";
#endif

[
    object,
    oleautomation,
    uuid(d1c51d00-8b48-11d5-006d-00c04fa12c4a),
    pointer_default(unique)
]
interface IDecode : IUnknown
    {
    HRESULT GetErrorString ([in]HRESULT errorNum, [out]BSTR * pStr);
    };


[
    uuid(056423e0-8b49-11d5-00c9-00c04fa12c4a),
    version(1.0),
    helpstring("CoErrorDecode Type Library")
]
library CoErrorDecodeLib
    {
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
	uuid(0563fcd0-8b49-11d5-0003-00c04fa12c4a),
	helpstring("CoErrorDecode Class")
    ]
    coclass CoErrorDecode
	{
        [default] interface IDecode;
	};
};
