h40031
s 00000/00000/00000
d R 1.2 01/11/19 19:00:47 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 1 0 clas/cmon/sda.inc/sdaparam.inc
e
s 00008/00000/00000
d D 1.1 01/11/19 19:00:46 boiarino 1 0
c date and time created 01/11/19 19:00:46 by boiarino
e
u
U
f e 0
t
T
I 1
c some parameters from sdaanal.inc etc
c
      INTEGER nsgmx, nsgcmx, nclmx, ntrmx, nplane
      PARAMETER (nsgmx=60, nsgcmx=30, nclmx=100, ntrmx=500, nplane=46)
c
      INTEGER nlnkvect, nlnkec
      PARAMETER (nlnkvect=16, nlnkec=12)
c
E 1
