#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../.. T_A=vxWorks-ppc604_long  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../.. T_A=vxWorks-ppc604_long  $@

force:  ;
