
#  makefile
#  vhg, aug-2000


all:
	cd c_cntl;    $(MAKE) all
 
clean:
	cd c_cntl;    $(MAKE) clean
 
distclean:
	cd c_cntl;    $(MAKE) distclean

 
install: exports
exports:
	cd c_cntl;    $(MAKE) exports

check:
	cd c_cntl;    $(MAKE) check

 

