#
# dchv/dchv
#
SHELL = /bin/sh

install:
	if (test ! -d $(CLON)/common/scripts/dchv_util); then \
		mkdir $(CLON)/common/scripts/dchv_util; \
	fi
	cp dchv $(CLON)/common/scripts/
##	cp dchv_light $(CLON)/common/scripts/
	cp dctimeline $(CLON)/common/scripts/
	cp dchv_mon $(CLON)/common/scripts/
	cp *.tcl $(CLON)/common/scripts/dchv_util
	cp *.h $(CLON)/common/scripts/dchv_util
	cp genfile4tg $(CLON)/common/scripts/


