/*
** Generated by X-Designer
*/
#ifndef _test_h
#define _test_h

#define XD_MOTIF

#include <xdclass.h>


extern Widget shell1;
extern Widget OutFrame;
extern Widget OutLabel;
extern Widget outForm;
extern Widget fileFr;
extern Widget FileForm;
extern Widget FileName;
extern Widget FileEnable;
extern Widget fileLabel;
extern Widget tokenFr;
extern Widget tokenForm;
extern Widget tokenInterval;
extern Widget tokenLabel;
extern Widget bootFr;
extern Widget bootLabel;
extern Widget updFr;
extern Widget updateRate;
extern Widget updLabel;
extern Widget monFr;
extern Widget monLabel;

extern void create_shell1 (Display *display, char *app_name, int app_argc, char **app_argv);

#endif







