/* This file has been generated from the following Tcl source file(s): CODA_class.tcl
 * on Thu Jun 12 14:53:52 EDT 2008 by boiarino
 */
#include <tcl.h>
static char initCmdCODA[] =
    "\n"
    "class CODA {\n"
    "    public  variable local_input \"\"\n"
    "\n"
    "    public  variable state \"unknown\"\n"
    "    public  variable name  \"unknown\"\n"
    "    public  variable debug\n"
    "    public  variable nlongs \n"
    "    public  variable nevents \n"
    "\n"
    "    public  variable event_rate 0\n"
    "    public  variable data_rate 0\n"
    "\n"
    "    public  variable codaid  \n"
    "    public  variable targetOK \n"
    "    public  variable session\n"
    "\n"
    "    method   status         {{arg \"\"}}   {}\n"
    "    method   statusstate    {{arg \"\"}}   {}\n"
    "    method   download       {}       {}\n"
    "    method   prestart       {}       {}\n"
    "    method   go             {}       {}\n"
    "    method   end            {}       {}\n"
    "    method   pause          {}       {}\n"
    "\n"
    "    method   exit           {}       {}\n"
    "\n"
    "    method   version        {}       {\n"
    "	global tcl_modules coda_version\n"
    "	puts \"CODA version $coda_version\"\n"
    "	puts \"==========================\"\n"
    "	foreach module $tcl_modules  {\n"
    "	    puts \"module : [lindex $module 0]\"\n"
    "	    if {\"[lindex $module 2]\" != \"\"} {\n"
    "		puts \"         Compiled by [lindex $module 2] on [lindex $module 1]\"\n"
    "	    }\n"
    "	    puts \"         CVS info :\"\n"
    "	    set cvs [lindex $module 3]\n"
    "	    puts \"                   File version: [lindex $cvs 2]\"\n"
    "	    puts \"                   Commit by   : [lindex $cvs 5]\"\n"
    "	    puts \"                   Date        : [lindex $cvs 3]\"\n"
    "	    puts \"                   Time        : [lindex $cvs 4]\"\n"
    "	    puts \"                   File status : [lindex $cvs 6]\"\n"
    "	}\n"
    "    }\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "    method   statistics {} {\n"
    "	return [list $nevents $event_rate $nlongs $data_rate]\n"
    "    }\n"
    "\n"
    "    method   stat_nevents {} {\n"
    "	return $nevents\n"
    "    }\n"
    "    method   stat_event_rate {} {\n"
    "	return $event_rate\n"
    "    }\n"
    "    method   stat_nlongs {} {\n"
    "	return $nlongs\n"
    "    }\n"
    "    method   stat_data_rate {} {\n"
    "	return $data_rate\n"
    "    }\n"
    "\n"
    "    constructor             {sess} { \n"
    "	global os_name\n"
    "	set session $sess\n"
    "\n"
    "    } @coda_constructor\n"
    "\n"
    "    destructor              @coda_destructor\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "body CODA::status {{arg \"\"}} { \n"
    "    puts \"Sergey: CODA::status reached\"\n"
    "    if { \"$arg\" != \"\" } {\n"
    "      $this configure -state $arg\n"
    "	  database query \"UPDATE process SET state='$arg' WHERE name='$name'\"\n"
    "    }\n"
    "	database query \"SELECT state FROM process WHERE name='$name'\"\n"
    "    set res [database get next]\n"
    "    set state [lindex $res 0]\n"
    "    puts \"Sergey: state=$state\"\n"
    "    return $state\n"
    "}\n"
    "\n"
    "\n"
    "body CODA::statusstate {{arg \"\"}} { \n"
    "    puts \"Sergey: CODA::status reached\"\n"
    "    if { \"$arg\" != \"\" } {\n"
    "      $this configure -state $arg\n"
    "    }\n"
    "    return $state\n"
    "}\n"
    "\n"
    "\n"
    "body CODA::download {} {\n"
    "puts \"download 111\"\n"
    "    status downloaded\n"
    "puts \"download 222\"\n"
    "    return $state\n"
    "}\n"
    "\n"
    "body CODA::prestart {} {\n"
    "    status paused\n"
    "    return $state\n"
    "}\n"
    "\n"
    "body CODA::go {} {\n"
    "    status active\n"
    "    return $state\n"
    "}\n"
    "\n"
    "body CODA::end {} {\n"
    "    status downloaded\n"
    "    return $state\n"
    "}\n"
    "\n"
    "body CODA::pause {} {\n"
    "    status paused\n"
    "    return $state\n"
    "}\n"
    "\n"
    "body CODA::exit {} {\n"
    "    global os_name\n"
    "\n"
    "    end\n"
    "    set state configured\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    ;
/* End of Tcl code */
/* Init routine to drag this code into our program...*/
int CODA_class_Init (Tcl_Interp *interp)
{
    if (Tcl_Eval(interp,initCmdCODA) != 0) {
    char *val;
    fprintf (stderr, "ERROR:\n      %s\n", interp->result);
    val = Tcl_GetVar(interp, "errorInfo", TCL_GLOBAL_ONLY);
    fprintf (stderr, "TclStack:\n      %s\n",val);
       return TCL_ERROR;
    }
    return TCL_OK;
}
/* End of C code */
