#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#
# by Vardan Gyurjyan. CLAS online group. 05.24.99
# resume the run

if { [llength $argv] != 0 } {
  set roc $argv
} else {
  set roc "clastrig2"
}

set err [catch {set stat [exec tcpClient $roc resume_run]}]

if {$err!=0} {
  puts "Error resuming the run."
} else {
  puts "Run is resumed."
}

exit $err
