#!/bin/csh

#  ejw, 5-oct-01


if ($1 == start) then

  ssh -n $CLON_DAQ "(process_manager) >>& $CLON_LOG/processes/process_manager.log &" &

else if ($1 == stop) then

  stop_proc -n $CLON_DAQ -p process_manager >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
