#!/bin/csh

#  ejw, 24-sep-01


if ($1 == start) then

  ssh -n $CLON_DAQ "alarm_server -a $2 >>& $CLON_LOG/run_log/alarm_server.log &" &

else if ($1 == stop) then

  stop_ipc_proc -a $2 -i alarm_server -n $CLON_DAQ -p alarm_server >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
