#!/bin/csh

#  ejw, 27-jun-03


if ($1 == start) then

  ssh -n $CLON_DAQ "(setenv EPICS_CAS_INTF_ADDR_LIST $CLON_DAQ.jlab.org; clas_epics_server -a $2) >>& $CLON_LOG/epics/clas_epics_server.log &" &

else if ($1 == stop) then

  stop_ipc_proc -a $2 -i clas_epics_server -n $CLON_DAQ -p clas_epics_server >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
