#!/bin/csh

#  ejw, 28-sep-01

set daq  = `echo $CLON_DAQ  | sed "s/^....//"`
set mon2 = `echo $CLON_MON2 | sed "s/^....//"`


if ($1 == start) then

###  ssh -n $CLON_DAQ "et_2_et_10_02 /tmp/et_sys_clasprod /tmp/et_sys_clasprod ET2ET02 >>& $CLON_LOG/run_log/et2et_${daq}_${mon2}_$3.log &" & 
  ssh -n $CLON_DAQ "et_2_et_10_02 clon10:/tmp/et_sys_clasprod clonmon2:/tmp/et_sys_clasprod ET2ET02 >>& $CLON_LOG/run_log/et2et_${daq}_${mon2}_$3.log &" & 

else if ($1 == stop) then

#  use -match as there are multiple et2et procs running
###  stop_ipc_proc -a $2 -i et2et_daq_mon2_$2 -n $CLON_DAQ -p et_2_et_10_02 -match ET2ET${mon2} -s 90 >& /dev/null
###  stop_proc -n $CLON_DAQ -p et_2_et_10_02 -match ET2ET${mon2} >& /dev/null
  stop_proc -n $CLON_DAQ -p et_2_et_10_02 >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif

