#!/bin/csh

#  ejw, 24-sep-01


if ($1 == start) then

  ssh -n $CLON_DAQ "alarm_handler -a $2 >>& $CLON_LOG/run_log/alarm_handler.log &" &

else if ($1 == stop) then

  stop_ipc_proc -a $2 -i alarm_handler -n $CLON_DAQ -p alarm_handler >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
