#!/bin/tcsh -f
#
#  ctoftest_exit - stops all DAQ processes at clon00
#
#  SP, 18-Jul-2006


if ( $HOST != clon00 ) then
  echo ""
  echo " You should be logged into clon00 to run this program."
  echo ""
  exit (1)
endif
echo ""


echo " Stop EB on clon00"
set x = `"ps -ef | grep coda_eb | grep ctoftest | grep -v grep " `
if ($#x > 1) then
  set x2 = $x[2]
  set x = `kill -9 $x2`
  if ($#x > 1) then
    echo "$x"
  endif
else
  echo "$x"
endif


echo " Stop ER on clon00"
set x = ` "ps -ef | grep coda_er | grep ctoftest | grep -v grep " `
if ($#x > 1) then
  set x2 = $x[2]
  set x = `kill -9 $x2`
  if ($#x > 1) then
    echo "$x"
  endif
else
  echo "$x"
endif


echo " Stop RunControl on clon00"
set x = `ps -ef | grep runcontrol | grep ctoftest | grep -v grep | awk '{print $2}' `
if ($#x > 0) then
  kill -9 $x
endif


echo " Stop rcServer on clon00"
set x = `/usr/ucb/ps -auxwww | grep rcServer | grep ctoftest | grep -v grep | awk '{print $2}' `
if ($#x > 0) then
  kill -9 $x
endif


echo " Stop ET on clon00"
set x = `ps -ef | grep et_start | grep et_sys_ctoftest | grep -v grep`
if ($#x > 1) then
  set x2 = $x[2]
  set x = `kill -9 $x2`
  if ($#x > 1) then
    echo "$x"
  endif
else
  echo "$x"
endif


echo " Remove ET system file"
sleep 2
set x = `rm -f /tmp/et_sys_ctoftest`



#********************************************************************


echo ""
echo " Kill terminals:"


set x = `ps -ef | grep xterm | grep ET_ctoftest | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 ET_ctoftest done"


set x = `ps -ef | grep xterm | grep EB_ctoftest | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 EB_ctoftest done"


set x = `ps -ef | grep xterm | grep ER_ctoftest | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 ER_ctoftest done"


set x = `ps -ef | grep xterm | grep runcontrol_ctoftest | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 runcontrol_ctoftest done"


##set x = `ps -ef | grep xterm | grep CRATE_ctoftest | awk '{print $2}'`
##if ($#x > 0) then
##  kill -9 $x
##endif
##echo "                 CRATE_ctoftest done"



echo ""
echo "ctoftest_exit done."
echo ""


exit

