#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  Get board status for FASTBUS module in inputed "roc" & "slot":
#    prn=1: Check and print Full Board Status with compare
#           settings of CSRs to CSRs-default;
#    prn=2: NO PRINTS, all possible errors collect in return,
#           Check only BUSY status,
#           return "OK", "Busy ..." or "Error: ..." with short
#           info what kind of error was occurred;
#    prn=0: Board Check without compare CSRs settings,
#           print only Error messages if some errors occurred,
#           return (check result).
#
#         by Serguei P.
#         Last update 12/28/2001

set flag 0
set roc_name " dc1 dc2 dc3 dc4 dc5 dc6 dc7 dc8 dc9 dc10 dc11\
	      lac1 tage tlv1 cc1 cc2 ec1 ec2 sc1\
	      croctest1 "


set inp_str [split $argv " "]
set inp_N [llength $inp_str]

#***  Check input parameters ***
if { ($inp_N != 2) && ($inp_N != 3) } { set flag 1
} elseif { $inp_N == 2 } {
  set roc  [string tolower [lindex $inp_str 0]]
  set slot [lindex $inp_str 1]
  set prn 1
  if { ![string match "* $roc *" $roc_name] } { set flag 2
  } elseif { ($slot < 0) || ($slot > 25) } { set flag 3 }
} elseif { $inp_N == 3 } {
  set roc  [string tolower [lindex $inp_str 0]]
  set slot [lindex $inp_str 1]
  set prn [lindex $inp_str 2]
  if { ![string match "* $roc *" $roc_name] } { set flag 4
  } elseif { ($slot < 0) || ($slot > 25) }  { set flag 5
  } elseif { ($prn < 0) || ($prn > 2) } { set flag 6 }
}
#puts "flag=$flag."
#puts "inp_str=$inp_str"
#puts "inp_N=$inp_N"
#puts "roc=$roc;"
#puts "slot=$slot;"
#puts "prn=$prn;"


#***  Print help message ***
if { $flag != 0 } {
 puts ""
 puts "  Usage: fb_board_stats roc slot prn"
 puts "         ---------------------------"
 puts "  Where \"roc\"  - ROC name from the following list:"
 puts "                   dc1 dc2 dc3 dc4 dc5 dc6 dc7 dc8 dc9 dc10 dc11"
 puts "                   lac1 tage tlv1 cc1 ec1 ec2 sc1"
 puts "                   croctest1;"
 puts "        \"slot\" - Fastbus slot number (0-25);"
 puts "        \"prn\"  - print flag, can be skiped (default=1),"
 puts "                   (1) = Check and Print Full Board Status,"
 puts "                   (2) = NO PRINTS, Check only BUSY status,"
 puts "                   (0) = Check without compare CSRs settings to default."
 puts ""
 exit
}


set result "\n error: Can't get result for csr_conf_settings() \n"
catch {set result [exec tcpClient $roc csr_conf_settings("$roc",0)]}
puts "$result"

set result "\n error: Can't get result for fb_board_stats() \n"
catch {set result [exec tcpClient $roc fb_board_stats($slot,$prn)]}
puts "$result"


exit

