#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  get_ts_state

#   returns TS state register

#   ejw, 16-jul-97


#  read ts control/status word
set err [catch {set status [exec tcpClient clastrig2 ts_state]}]

if {$err!=0} {puts "DP_ask error: $err"} else {puts "$status"}

exit
