#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  get_ts_program

#   reads trigger supervisor program in 2 pieces
#    and stores them in $CLAS_PARMS/ts/ts_program.txt

#   ejw, 19-may-97



#  get date
set date [exec date]

#  open output file
set pfile [open $env(CLON_PARMS)/ts/current_ts_program.txt w]

#  write date to file
puts $pfile "\n#  get_ts_program run on $date\n"
puts $pfile   "#    E.Wolin, 17-jul-97\n"

#  read ts program


set err [catch {puts -nonewline $pfile [exec tcpClient clastrig2 ts_prog]} msg]


if {$err!=0} {
    puts $pfile "\n#  *** Unable to read TS ***\n"
    puts $pfile "\n$msg"
}

#  close file
close $pfile


#  done
exit
