#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  get_ts_l1mask

#   exit code is TS level 1 trigger mask
#   also writes file of l1 mask bits to $CLON_PARMS/ts/current_l1mask.txt

#   ejw, 14-oct-97


#  get date
set date [exec date]


#  open output file
set pfile [open $env(CLON_PARMS)/ts/current_ts_l1mask.txt w]
puts $pfile "\n#  get_ts_l1mask run on $date\n"
puts $pfile   "#    E.Wolin, 17-jul-97\n\n"




#  read ts control register
set err [catch {set status [exec tcpClient clastrig2 ts_control]}]

#  print register,mask and exit with mask
if {$err!=0} {
    puts $pfile "Unable to read TS control register, err: $err"
    close $pfile
    exit -1

} else {
    set mask [expr (0x$status>>1)&0xfff]
    puts $pfile "*L1MASK*"
    for {set i 1} {$i<13} {incr i} {
	puts -nonewline $pfile "[expr (0x$status>>$i)&0x1] "
    }
    puts $pfile "\n\n"
    puts $pfile "*TSREG*"
    puts $pfile "$status\n"
    close $pfile
    exit [format "%d" $mask]
}





