#
# Makefile for scripts/
#

all:
	@echo "Nothing to compile"


install:
	@echo "Install scripts"
	-mkdir -p $(CODA)/common/scripts
##	@cp -rf * $(CODA)/common/scripts
	@cp -f * $(CODA)/common/scripts
	rm -f $(CODA)/common/scripts/Makefile

clean:
	@echo "Nothing to clean"
