#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  reset_ts_l1enable

#   resets ts l1 enable bit

#   ejw, 16-feb-98


set err [catch {set stat [exec tcpClient clastrig2 reset_ts_l1_bit]}]

if {$err!=0} {puts -1} else {puts $stat}	
exit


