#!/bin/csh -f


#***  Print help message if -h or -help specified ***
if ($#argv != 0 ) then 
# echo $#argv
  if (($argv[1] == "-h") || ($argv[1] == "-help")) then 
    echo ""
    echo "  Usage: roc_boot_renew roc_name"
    echo "  ======"
    echo "    List of possible ROC names:"
    echo "    ---------------------------"
    echo "       dc1 dc2 dc3 dc4 dc5 dc6 dc7 dc8 dc9 dc10 dc11"
    echo "       lac1 tage tage3 cc1 cc2 ec1 ec2 sc1"
    echo "       scaler1 scaler2 scaler3 scaler4 polar"
    echo "       clastrig2 dccntrl camac1 camac2 camac3"
    echo "       sc-laser1 ioctorus1 clasgas"
    echo "       classc1 classc2 classc3 classc4 classc5 classc8 classc12"
    echo "       pretrig1 pretrig2 croctest1 croctest2 croctest4"
    echo "       primexts primexroc1"
    echo ""
    exit (0)
  endif
endif


set roc = $1
set roc_name = ( dc1 dc2 dc3 dc4 dc5 dc6 dc7 dc8 dc9 dc10 dc11 \
                 lac1 tage tage3 cc1 cc2 ec1 ec2 sc1 \
                 scaler1 scaler2 scaler3 scaler4 polar \
                 clastrig2 dccntrl camac1 camac2 camac3 \
                 sc-laser1 ioctorus1 clasgas \
                 classc1 classc2 classc3 classc4 classc5 classc8 classc12 \
                 pretrig1 pretrig2 croctest1 croctest2 croctest4 \
                 primexts primexroc1)

# ROC="iochlb" was in previous roc_reboot script,
# but now it is out of our control


#*** Check ROC name ***
set ii = -1
foreach word ($roc_name)
  if ( $roc == $word ) set ii = 0
end
if ( $ii == -1 ) then
  echo ""
  echo " Unknown ROC. Please check the ROC name."
  echo "              Use -h for help."
  echo ""
  exit (-1)
endif


#*** Start boot_renew script ***

if ($HOST != "$CLON_DAQ") then
  ssh -n $CLON_DAQ $CLON_BIN/beg_boot_renew $1
else
  $CLON_BIN/beg_boot_renew $1
endif


exit (0)
