#!/bin/sh
#\
exec /usr/bin/wish -f "$0" ${1+"$@"}
#

#  TOF_get_mask_position

#  SP, 03-Jul-2003


#***  Check input parameters ***
set flag 0
if { $argc!=1 }                     { set flag 1
} else {
  if { ($argv < 1) || ($argv > 4) } { set flag 2 }
}

#***  Print help message ***
if { $flag != 0 } {
 puts "\n Usage: TOF_get_mask_position laser_number"
 puts "        -------------------------------------"
 puts " Where \"laser_number\" form the list (1,2,3,4) \n"
 exit
}

#***  Set roc name ***
if { $argv == 1 }  { set roc "camac1"
} else             { set roc "sc-laser1" }


set result "\n error: Can't get result for get_mask_position() \n"
catch {set result [exec tcpClient $roc get_mask_position($argv)]}
puts "$result"


exit

