#!/bin/tcsh -f
#
#  wolfram_start - start DAQ on wolfram (ELL building)
#                  Youri Sharabian's test setup
#
#  SP, 17-Sep-2007


#if ($HOST != "wolfram") then
#  echo ""
#  echo " You should be logged into wolfram"
#  echo ""
#  exit (1)
#endif

#
###source /home/boiarino/.cshrc
#
# clon00:
#et_start -n 1000 -s 100000 -f /tmp/et_sys_claswolf
#
# clon00:
#coda_eb -session claswolf -objects "EB2 CDEB" -i
#
# clon00:
#coda_er -session claswolf -objects "ER2 ER" -i
#
# wolfram:
#cu -l /dev/cua/b
# ( to exit: ~. )
#
# wolfram:
# runcontrol
#
set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_wolfram"
set EB_t  = "-T EB_wolfram"
set ER_t  = "-T ER_wolfram"
set RC_t  = "-T runcontrol_wolfram"
##set XT1_t = "-T VME_wolfram"

set ET   = wolfram_et.tcl
set EB   = wolfram_eb.tcl
set ER   = wolfram_er.tcl
set RC   = wolfram_rc.tcl
##set XT   = wolfram_prxt.tcl


echo " Start RunControl"
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC >& /dev/null &`

echo ""
echo " Start ET"
set color = "-bg blue -fg white -sb -sl 5000"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER >& /dev/null &`

##echo " Start serial connection to VME_wolfram"
##set roc   = "b"
##set ypos  = `expr $ypos + $yinc`
##set geom  = "-geometry 70x9+$xpos+"
##set color = "-sb -sl 5000"
##set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $roc >& /dev/null &`

echo ""
echo "wolfram_start done."
echo ""

