#!/bin/csh -f
#
#  wolfram_exit - stops all DAQ processes on wolfram
#
#  SP, 17-Sep-2007


#if ($HOST != "wolfram") then
#  echo ""
#  echo " You should be logged into wolfram"
#  echo ""
#  exit (1)
#endif
#echo ""


echo " Stop EB"
#set x = `ssh clon00 "ps -ef | grep coda_eb | grep claswolf | grep -v grep " `
set x = `ps -ef | grep coda_eb | grep claswolf | grep -v grep `
if ($#x > 1) then
  set x2 = $x[2]
#  set x = `ssh clon00 "kill -9 $x2" `
  set x = `kill -9 $x2 `
  if ($#x > 1) then
    echo "$x"
  endif
else
  echo "$x"
endif


echo " Stop ER"
#set x = `ssh clon00 "ps -ef | grep coda_er | grep claswolf | grep -v grep " `
set x = `ps -ef | grep coda_er | grep claswolf | grep -v grep `
if ($#x > 1) then
  set x2 = $x[2]
#  set x = `ssh clon00 "kill -9 $x2" `
  set x = `kill -9 $x2 `
  if ($#x > 1) then
    echo "$x"
  endif
else
  echo "$x"
endif


echo " Stop RunControl"
set x = `ps -ef | grep runcontrol | grep claswolf | grep -v grep | awk '{print $2}' `
if ($#x > 0) then
  kill -9 $x
endif


echo " Stop rcServer"
set x = `/usr/ucb/ps -auxwww | grep rcServer | grep claswolf | grep -v grep | awk '{print $2}' `
if ($#x > 0) then
  kill -9 $x
endif


echo " Stop ET"
set x = `ps -ef | grep et_start | grep et_sys_claswolf | grep -v grep | awk '{print $2}' `
if ($#x > 0) then
  kill -9 $x
endif
#set x = `ssh clon00 "ps -ef | grep et_start | grep et_sys_claswolf | grep -v grep " `
#if ($#x > 1) then
#  set x2 = $x[2]
#  set x = `ssh clon00 "kill -9 $x2" `
#  set x = `kill -9 $x2 `
#  if ($#x > 1) then
#    echo "$x"
#  endif
#else
#  echo "$x"
#endif


echo " Remove ET system file"
sleep 2
#set x = `ssh clon00 "rm -f /tmp/et_sys_claswolf " `
set x = `rm -f /tmp/et_sys_claswolf `



#********************************************************************


echo ""
echo " Kill terminals:"


set x = `ps -ef | grep xterm | grep ET_wolfram | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 ET_wolfram done"


set x = `ps -ef | grep xterm | grep EB_wolfram | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 EB_wolfram done"


set x = `ps -ef | grep xterm | grep ER_wolfram | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 ER_wolfram done"


set x = `ps -ef | grep xterm | grep runcontrol_wolfram | awk '{print $2}'`
if ($#x > 0) then
  kill -9 $x
endif
echo "                 runcontrol_wolfram done"


##set x = `ps -ef | grep xterm | grep VME_wolfram | awk '{print $2}'`
##if ($#x > 0) then
##  kill -9 $x
##endif
##echo "                 VME_wolfram done"



echo ""
echo "wolfram_exit done."
echo ""


exit
