#!/bin/bash






#pwd
#source ~sytnik/.cshrc


O.linux-x86/ioccaenold startup.all &> ~/.crontab_ioccaenold &
#O.linux-x86/ioccaen startup.all &> /home/sytnik/temp1.txt &

#echo hhh > /misc/home/sytnik/ioc_watchdog/t1.txt
#echo $DIM_DNS_NODE > /misc/home/sytnik/ioc_watchdog/t1.txt