#!/bin/tcsh
cau <<+
put MTIRBCK.HIHI 7800
put MTIRBCK.HIGH 7500.
put MTIRBCK.LOW 1000.
put MTIRBCK.LOLO 500.
put MTIRBCK.HHSV MAJOR
put MTIRBCK.HSV MINOR
put MTIRBCK.LSV MINOR
put MTIRBCK.LLSV MAJOR

#put VMP2C24SPD.HIHI 101.
#put VMP2C24SPD.HIGH 101.
#put VMP2C24SPD.LOW 80.
#put VMP2C24SPD.LOLO 50.
#put VMP2C24SPD.HHSV NO_ALARM
#put VMP2C24SPD.HSV NO_ALARM
#put VMP2C24SPD.LSV MINOR
#put VMP2C24SPD.LLSV MAJOR

#put VCG2C21.HIHI 5.
#put VCG2C21.HIGH 4.
#put VCG2C21.LOW 0.
#put VCG2C21.LOLO 0.
#put VCG2C21.HHSV MAJOR
#put VCG2C21.HSV MINOR
#put VCG2C21.LSV NO_ALARM
#put VCG2C21.LLSV NO_ALARM

#put VCG2H01.HIHI 7.
#put VCG2H01.HIGH 6.
#put VCG2H01.LOW 0.
#put VCG2H01.LOLO 0.
#put VCG2H01.HHSV MAJOR
#put VCG2H01.HSV MINOR
#put VCG2H01.LSV NO_ALARM
#put VCG2H01.LLSV NO_ALARM

put scaler_cS2b.HIHI  999999
put scaler_cS2b.HIGH  999999
put scaler_cS2b.LOW   7
put scaler_cS2b.LOLO  5
put scaler_cS2b.HHSV NO_ALARM
put scaler_cS2b.HSV NO_ALARM
put scaler_cS2b.LSV MINOR
put scaler_cS2b.LLSV MAJOR


put scaler_cS3b.HIHI  999999
put scaler_cS3b.HIGH  999999
put scaler_cS3b.LOW   7
put scaler_cS3b.LOLO  5
put scaler_cS3b.HHSV NO_ALARM
put scaler_cS3b.HSV NO_ALARM
put scaler_cS3b.LSV MINOR
put scaler_cS3b.LLSV MAJOR


put scaler_cS4b.HIHI  999999
put scaler_cS4b.HIGH  999999
put scaler_cS4b.LOW   7
put scaler_cS4b.LOLO  5
put scaler_cS4b.HHSV NO_ALARM
put scaler_cS4b.HSV NO_ALARM
put scaler_cS4b.LSV MINOR
put scaler_cS4b.LLSV MAJOR


put scaler_cS5b.HIHI  999999
put scaler_cS5b.HIGH  999999
put scaler_cS5b.LOW   7
put scaler_cS5b.LOLO  5
put scaler_cS5b.HHSV NO_ALARM
put scaler_cS5b.HSV NO_ALARM
put scaler_cS5b.LSV MINOR
put scaler_cS5b.LLSV MAJOR


put scaler_cS6b.HIHI  999999
put scaler_cS6b.HIGH  999999
put scaler_cS6b.LOW   7
put scaler_cS6b.LOLO  5
put scaler_cS6b.HHSV NO_ALARM
put scaler_cS6b.HSV NO_ALARM
put scaler_cS6b.LSV MINOR
put scaler_cS6b.LLSV MAJOR


put scaler_cS7b.HIHI  999999
put scaler_cS7b.HIGH  999999
put scaler_cS7b.LOW   7
put scaler_cS7b.LOLO  5
put scaler_cS7b.HHSV NO_ALARM
put scaler_cS7b.HSV NO_ALARM
put scaler_cS7b.LSV MINOR
put scaler_cS7b.LLSV MAJOR


put scaler_cS8b.HIHI  999999
put scaler_cS8b.HIGH  999999
put scaler_cS8b.LOW   7
put scaler_cS8b.LOLO  5
put scaler_cS8b.HHSV NO_ALARM
put scaler_cS8b.HSV NO_ALARM
put scaler_cS8b.LSV MINOR
put scaler_cS8b.LLSV MAJOR


put scaler_cS9b.HIHI  999999
put scaler_cS9b.HIGH  999999
put scaler_cS9b.LOW   7
put scaler_cS9b.LOLO  5
put scaler_cS9b.HHSV NO_ALARM
put scaler_cS9b.HSV NO_ALARM
put scaler_cS9b.LSV MINOR
put scaler_cS9b.LLSV MAJOR


put scaler_cS10b.HIHI  999999
put scaler_cS10b.HIGH  999999
put scaler_cS10b.LOW   7
put scaler_cS10b.LOLO  5
put scaler_cS10b.HHSV NO_ALARM
put scaler_cS10b.HSV NO_ALARM
put scaler_cS10b.LSV MINOR
put scaler_cS10b.LLSV MAJOR


put scaler_cS11b.HIHI  999999
put scaler_cS11b.HIGH  999999
put scaler_cS11b.LOW   7
put scaler_cS11b.LOLO  5
put scaler_cS11b.HHSV NO_ALARM
put scaler_cS11b.HSV NO_ALARM
put scaler_cS11b.LSV MINOR
put scaler_cS11b.LLSV MAJOR


put scaler_cS12b.HIHI  999999
put scaler_cS12b.HIGH  999999
put scaler_cS12b.LOW   7
put scaler_cS12b.LOLO  5
put scaler_cS12b.HHSV NO_ALARM
put scaler_cS12b.HSV NO_ALARM
put scaler_cS12b.LSV MINOR
put scaler_cS12b.LLSV MAJOR


put scaler_cS13b.HIHI  999999
put scaler_cS13b.HIGH  999999
put scaler_cS13b.LOW   7
put scaler_cS13b.LOLO  5
put scaler_cS13b.HHSV NO_ALARM
put scaler_cS13b.HSV NO_ALARM
put scaler_cS13b.LSV MINOR
put scaler_cS13b.LLSV MAJOR

quit
+
exit
