# Production HV configuration

HV_CLAS = hv.alhConfig

HV_CLAS_MF     =$(APP)/hvca/medm/alh/bm_mf_02_01.alhConfig_mf \
		$(APP)/hvca/medm/alh/ec_caen_mf_04_01.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecn_mf_06_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecn_mf_08_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecs_mf_03_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecs_mf_04_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecs_mf_05_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/ccecs_mf_07_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/scf_mf_09_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/scf_mf_10_05.alhConfig_mf \
		$(APP)/hvca/medm/alh/dc_mf_01_10.alhConfig_mf \
		$(APP)/hvca/medm/alh/dc_mf_03_10.alhConfig_mf \
		$(APP)/hvca/medm/alh/dc_mf_04_10.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_03_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_04_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_06_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_01_12.alhConfig_mf 
#		$(APP)/hvca/medm/alh/lac_mf_01_09.alhConfig_mf \
#		$(APP)/hvca/medm/alh/lac_mf_02_09.alhConfig_mf \
#		$(APP)/hvca/medm/alh/lac_mf_03_09.alhConfig_mf \
#		$(APP)/hvca/medm/alh/lac_mf_04_09.alhConfig_mf \
#		$(APP)/hvca/medm/alh/bmtasc_mf_07_12.alhConfig_mf \
#		$(APP)/hvca/medm/alh/bmtasc_mf_08_12.alhConfig_mf 
#		$(APP)/hvca/medm/alh/bmtasc_mf_02_12.alhConfig_mf \

HV_CLAS_CONFIG =$(APP)/hvca/medm/alh/bm_beam_counter.alhConfig \
		$(APP)/hvca/medm/alh/ec_caen_ec_s1_caen.alhConfig \
		$(APP)/hvca/medm/alh/ec_caen_ec_s2_caen.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_1.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_2.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_3.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_4.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_5.alhConfig \
		$(APP)/hvca/medm/alh/cc_cc_sect_6.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_1.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_2.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_3.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_4.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_5.alhConfig \
		$(APP)/hvca/medm/alh/ec_ec_sect_6.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_1.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_2.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_3.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_4.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_5.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_FC_sec_6.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_North_CS.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_South_CS.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_Space_2in.alhConfig \
		$(APP)/hvca/medm/alh/sc_TOF_Space_3in.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR1.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR2.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR3.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR4.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR5.alhConfig \
		$(APP)/hvca/medm/alh/dc_DC_SECTOR6.alhConfig \
		$(APP)/hvca/medm/alh/photon_ST.alhConfig 
#		$(APP)/hvca/medm/alh/lac_lac_s1_in.alhConfig \
#		$(APP)/hvca/medm/alh/lac_lac_s1_out.alhConfig \
#		$(APP)/hvca/medm/alh/lac_lac_s2_in.alhConfig \
#		$(APP)/hvca/medm/alh/lac_lac_s2_out.alhConfig 
#		$(APP)/hvca/medm/alh/photon_active_colimator.alhConfig \
#		$(APP)/hvca/medm/alh/photon_gamma_profiler.alhConfig \
#		$(APP)/hvca/medm/alh/photon_pair_spec_new.alhConfig \
#		$(APP)/hvca/medm/alh/photon_PrimEx_Profiler.alhConfig \
#		$(APP)/hvca/medm/alh/bm_hodoscope_LV.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_E_1.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_E_2.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_E_3.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_T_1.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_T_2.alhConfig \
#		$(APP)/hvca/medm/alh/ta_tagger_T_3.alhConfig 
#		$(APP)/hvca/medm/alh/bm_InnerCalorimeter_HV.alhConfig \

# Test setup in the counting room
HV_CR = hv_cr.alhConfig

HV_CR_MF     =	$(shell ls $(APP)/hvca/medm/alh/cr_mf_mf_??_99.alhConfig_mf)

HV_CR_CONFIG =	$(shell ls $(APP)/hvca/medm/alh/cr_mf_CR_?.alhConfig)




all: $(HV_CLAS) $(HV_CR) hv_primex.alhConfig

$(HV_CLAS): hv_header $(HV_CLAS_MF) $(HV_CLAS_CONFIG)
	$(RM) $@
	cat  $^ > $@

$(HV_CR): hv_header $(HV_CR_MF) $(HV_CR_CONFIG)
	$(RM) $@
	cat  $^ | sed -e 's/GROUP *HV/GROUP HV_CR/g' -e 's/GROUP   NULL  HV/GROUP   NULL  HV_CR/g' > $@

hv_primex.alhConfig: hv_header $(APP)/hvca/medm/alh/*.alhConfig* 
	$(RM) $@
	cat  hv_header \
		$(APP)/hvca/medm/alh/bmtasc_mf_01_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_02_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_07_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bmtasc_mf_08_12.alhConfig_mf \
		$(APP)/hvca/medm/alh/bm_mf_02_01.alhConfig_mf \
                $(APP)/hvca/medm/alh/bm_beam_counter.alhConfig \
                $(APP)/hvca/medm/alh/ta*.alhConfig \
		> $@

clean:
	$(RM) hv.alhConfig hv_primex.alhConfig

# end of makefile
