/* This file has been generated from the following Tcl source file(s): tkSteal.tcl
 * on Thu Oct  2 09:48:47 EDT 1997 by heyes
 */
#include <tcl.h>
static char initCmd[] = 
    "\n"
    "global tkSteal_priv\n"
    "set tkSteal_priv(debug) 0\n"
    "\n"
    " proc tkSteal_getarg {opts arg var} {\n"
    "  set ind [lsearch $opts [concat $arg *]]\n"
    "  if {$ind==-1} {\n"
    "    error \"ARG ERROR: application tried to find nonexistend arg \\\"$arg\\\"!\"\n"
    "  }\n"
    "  upvar 1 $var varr\n"
    "  set varr [lindex [lindex $opts $ind] 4]\n"
    "  if {\"[lindex [lindex $opts $ind] 3]\" ==\n"
    "      \"[lindex [lindex $opts $ind] 4]\"} {\n"
    "    return 0\n"
    "  } {\n"
    "    return 1\n"
    "  }\n"
    "}\n"
    "\n"
    " proc tkSteal_parseargs {cmdline descr args} {\n"
    "  if {$args!=\"\"} {upvar 1 [lindex $args 0] changed}\n"
    "  set changed {}\n"
    "  for {set i 0} {$i<[llength $cmdline]} {incr i} {\n"
    "    set name [lindex $cmdline $i]\n"
    "    while {[llength $name]>0} {\n"
    "      if {[llength $name]==1} {\n"
    "        set value [lindex $cmdline [expr $i+1]]\n"
    "        incr i\n"
    "      } else {\n"
    "        set value [lindex $name 1]\n"
    "        set name [lindex $name 0]\n"
    "      }\n"
    "      set ind [lsearch $descr [concat $name *]]\n"
    "      if {$ind==-1} {\n"
    "        set ind [lsearch $descr $name]\n"
    "        if {$ind==-1} {\n"
    "          error \"unknown option \\\"$name\\\"\"\n"
    "        }\n"
    "      }\n"
    "      lappend changed $name\n"
    "      set descr [lreplace $descr $ind $ind \\\n"
    "        [lreplace [lindex $descr $ind] 4 4 $value]]\n"
    "      set name [lreplace $name 0 1]\n"
    "    }\n"
    "  }\n"
    "  set new {}\n"
    "  foreach item $descr {\n"
    "    if {[llength $item]<=5} {\n"
    "      lappend new $item\n"
    "    } else {\n"
    "      set act [lindex $item 5]\n"
    "      regsub -all \"%\\(value\\)\" $act [lindex $item 3] act\n"
    "      set item [lreplace $item 3 3 [eval $act]]\n"
    "      set act [lindex $item 5]\n"
    "      regsub -all \"%\\(value\\)\" $act [lindex $item 4] act\n"
    "      lappend new [lreplace $item 4 4 [eval $act]]\n"
    "    }\n"
    "  }\n"
    "  return $new\n"
    "}\n"
    "\n"
    "global tkSteal_ARGUMENTS\n"
    "set tkSteal_ARGUMENTS {\n"
    "{-background    background    Background   #d9d9d9         #d9d9d9}\n"
    "{-borderwidth   borderWidth   BorderWidth  0               0}\n"
    "{-command       command       Command      {} {}}\n"
    "{-foreground    foreground    Foreground   black           black}\n"
    "{-font          font          Font         *-Courier-Medium-R-Normal-*-120-* *-Courier-Medium-R-Normal-*-120-*}\n"
    "{-name          name          Name         {}              {}}\n"
    "{-height        height        Height       20              20}\n"
    "{-relief        relief        Relief       flat            flat}\n"
    "{-stealwindowid stealWindowId WindowId     0               0}\n"
    "{-takefocus     takeFocus     TakeFocus    0               0}\n"
    "{-type          type          Type         frame           frame}\n"
    "{-width         width         Width        20              20}\n"
    "{-windowid      windowId      WindowId     {}              {}}}\n"
    "\n"
    "proc tkSteal {pathName args} {\n"
    "\n"
    "  global tk_library\n"
    "  global tkSteal_priv\n"
    "  global tkSteal_ARGUMENTS\n"
    "\n"
    "  catch \"xaccess\" result\n"
    "  if {![string match \"wrong # args*\" $result]} {\n"
    "    error \"tkSteal: the command xaccess is not available\"\n"
    "  }\n"
    "\n"
    "  set tkSteal_priv($pathName,initialized) 0\n"
    "  set tkSteal_priv($pathName,pid) 0\n"
    "  set tkSteal_priv($pathName,config) \\\n"
    "    [tkSteal_parseargs $args $tkSteal_ARGUMENTS]\n"
    "\n"
    "  frame $pathName -borderwidth 0 -class TkSteal\n"
    "  rename $pathName $pathName-internal\n"
    "  proc $pathName args \"\n"
    "return \\[eval tkSteal_command $pathName \\$args\\]\"\n"
    "\n"
    "  set index [lsearch $args -type]\n"
    "  if {$index != -1 && \"[lindex $args [expr $index + 1]]\" == \"frame\"} {\n"
    "    frame $pathName.cbl -borderwidth 0\n"
    "  } {\n"
    "    label $pathName.cbl -borderwidth 0 -padx 1 -pady 1\n"
    "  }\n"
    "  rename $pathName.cbl $pathName-cblinternal\n"
    "  proc $pathName.cbl args \"\n"
    "return \\[eval tkSteal_command $pathName \\$args\\]\"\n"
    "  pack $pathName.cbl -side top -fill both -expand 1\n"
    "\n"
    "  bind $pathName.cbl <Map> \"\n"
    "    tkSteal_start $pathName\"\n"
    "  bind $pathName.cbl <Destroy> \"\n"
    "    tkSteal_stop $pathName\"\n"
    "  bind $pathName.cbl <Expose> \"\n"
    "    $pathName redisplay\"\n"
    "  bind $pathName.cbl <Enter> \"\n"
    "    $pathName redisplay\"\n"
    "  bind $pathName.cbl <Motion> \"\n"
    "    $pathName redisplay\"\n"
    "  bind $pathName.cbl <Configure> \"\n"
    "    $pathName redisplay\"\n"
    "  bind $pathName.cbl <Leave> \"\n"
    "    $pathName redisplay\"\n"
    "\n"
    "  bind [winfo toplevel $pathName.cbl] <Configure> \"\n"
    "    $pathName redisplay\"\n"
    "  bind [winfo toplevel $pathName.cbl] <Motion> \"\n"
    "    $pathName redisplay\"\n"
    "  bind [winfo toplevel $pathName.cbl] <Leave> \"\n"
    "    $pathName redisplay\"\n"
    "  bind [winfo toplevel $pathName.cbl] <Enter> \"\n"
    "    $pathName redisplay\"\n"
    "\n"
    "  eval $pathName config $args\n"
    "}\n"
    "\n"
    " proc tkSteal_start {pathName} {\n"
    "  global env\n"
    "  global tkSteal_priv\n"
    "\n"
    "  if {$tkSteal_priv($pathName,initialized) || \"$pathName\" == \"\"} {\n"
    "    return\n"
    "  }\n"
    "\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -background background\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -borderwidth borderwidth\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -foreground foreground\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -font font\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -command command\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -name name\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -height height\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -relief relief\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -type type\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -width width\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -stealwindowid stealwindowid\n"
    "  tkSteal_getarg $tkSteal_priv($pathName,config) -windowid windowid\n"
    "\n"
    "  if {\"$command\" != \"\"} {\n"
    "    set newCommand $command\n"
    "    regsub -all {\\$background} $newCommand $background newCommand\n"
    "    regsub -all {\\$foreground} $newCommand $foreground newCommand\n"
    "    regsub -all {\\$font} $newCommand $font newCommand\n"
    "    regsub -all {\\$relief} $newCommand $relief newCommand\n"
    "    regsub -all {\\$width} $newCommand $width newCommand\n"
    "    regsub -all {\\$height} $newCommand $height newCommand\n"
    "    regsub -all {\\$name} $newCommand $name newCommand\n"
    "    regsub -all {\\$windowid} $newCommand $windowid newCommand\n"
    "    regsub -all {\\$stealwindowid} $newCommand [format %ld [winfo id $pathName.cbl]] newCommand\n"
    "    regsub -all {\\$\\{background\\}} $newCommand $background newCommand\n"
    "    regsub -all {\\$\\{foreground\\}} $newCommand $foreground newCommand\n"
    "    regsub -all {\\$\\{font\\}} $newCommand $font newCommand\n"
    "    regsub -all {\\$\\{relief\\}} $newCommand $relief newCommand\n"
    "    regsub -all {\\$\\{width\\}} $newCommand $width newCommand\n"
    "    regsub -all {\\$\\{height\\}} $newCommand $height newCommand\n"
    "    regsub -all {\\$\\{name\\}} $newCommand $name newCommand\n"
    "    regsub -all {\\$\\{windowid\\}} $newCommand $windowid newCommand\n"
    "    regsub -all {\\$\\{stealwindowid\\}} $newCommand [format %ld [winfo id $pathName.cbl]] newCommand\n"
    "    if {[catch \"eval exec $newCommand &\" result]} {\n"
    "      error $result\n"
    "    } {\n"
    "      set tkSteal_priv($pathName,pid) $result\n"
    "    }\n"
    "  }\n"
    "\n"
    "  $pathName-internal conf -background $background\n"
    "  $pathName-internal conf -borderwidth $borderwidth\n"
    "  $pathName-internal conf -relief $relief\n"
    "  $pathName-cblinternal conf -background $background\n"
    "  if {\"$type\" != \"frame\"} {\n"
    "    $pathName-cblinternal conf -padx 0\n"
    "    $pathName-cblinternal conf -pady 0\n"
    "  }\n"
    "  if {\"$width\" != \"\" && $width != 0} {\n"
    "    $pathName-cblinternal conf -width $width\n"
    "  }\n"
    "  if {\"$height\" != \"\" && $height != 0} {\n"
    "    $pathName-cblinternal conf -height $height\n"
    "  }\n"
    "     $pathName conf -stealwindowid [format %ld [winfo id $pathName.cbl]]\n"
    "     \n"
    "     if {\"$windowid\" != \"\"} {\n"
    "	 if {[catch \"xaccess eventreparent -parentwidget $pathName.cbl -windowid $windowid\" ret]} {\n"
    "      error \"tkSteal_start: $ret\"\n"
    "    }\n"
    "  } {\n"
    "    if {\"$name\" != \"\"} {\n"
    "      if {![catch \"xaccess eventreparent -parentwidget $pathName.cbl -windowname \\{$name\\}\" ret]} {\n"
    "	  $pathName conf -windowid $ret\n"
    "	  set windowid $ret\n"
    "      } {\n"
    "        error \"tkSteal_start: $ret\"\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "     puts [catch \"after 3000 xaccess eventmap -windowid $windowid\" ]\n"
    "     \n"
    "  set tkSteal_priv($pathName,initialized) 1\n"
    "  after 2000 $pathName redisplay\n"
    "}\n"
    "\n"
    " proc tkSteal_stop {pathName} {\n"
    "  global tkSteal_priv\n"
    "\n"
    "  catch \"rename $pathName-internal \\\"\\\"\"\n"
    "  catch \"rename $pathName-cblinternal \\\"\\\"\"\n"
    "  if {$tkSteal_priv($pathName,pid) != 0} {\n"
    "    catch \"exec kill $tkSteal_priv($pathName,pid)\"\n"
    "    set tkSteal_priv($pathName,pid) 0\n"
    "  }\n"
    "  set tkSteal_priv($pathName,initialized) 0\n"
    "  return \"\"\n"
    "}\n"
    "\n"
    " proc tkSteal_command {pathName minorCommand args} {\n"
    "  global tkSteal_priv\n"
    "\n"
    "  case $minorCommand {\n"
    "    {conf*} {\n"
    "      if {[llength $args] == 0} {\n"
    "        set result \"\"\n"
    "        foreach element $tkSteal_priv($pathName,config) {\n"
    "          lappend result [list [lindex $element 0] [lindex $element 1] [lindex $element 2] [lindex $element 3] [lindex $element 4]]\n"
    "        }\n"
    "        return $result\n"
    "      } {\n"
    "        if {[llength $args] == 1} {\n"
    "          set resourceIndex [lsearch $tkSteal_priv($pathName,config) $args*]\n"
    "          if {$resourceIndex != -1} {\n"
    "            set element [lindex $tkSteal_priv($pathName,config) $resourceIndex]\n"
    "            return [list [lindex $element 0] [lindex $element 1] [lindex $element 2] [lindex $element 3] [lindex $element 4]]\n"
    "          } {\n"
    "            error \"unknown resource: $args\"\n"
    "          }\n"
    "        } {\n"
    "          set tkSteal_priv($pathName,config) \\\n"
    "            [tkSteal_parseargs $args $tkSteal_priv($pathName,config)]\n"
    "          for {set counter 0} {$counter < [llength $args]} {incr counter} {\n"
    "            case [lindex $args $counter] {\n"
    "              {-back*} {\n"
    "                tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "                  -background background\n"
    "                $pathName-internal conf -background $background\n"
    "                $pathName-cblinternal conf -background $background\n"
    "              }\n"
    "              {-border*} {\n"
    "                tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "                  -borderwidth borderwidth\n"
    "                $pathName-internal conf -borderwidth $borderwidth\n"
    "              }\n"
    "              {-reli*} {\n"
    "                tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "                  -relief relief\n"
    "                $pathName-internal conf -relief $relief\n"
    "              }\n"
    "              {-heig*} {\n"
    "                tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "                  -height height\n"
    "                $pathName-cblinternal conf -height $height\n"
    "              }\n"
    "              {-widt*} {\n"
    "                tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "                  -width width\n"
    "                $pathName-cblinternal conf -width $width\n"
    "              }\n"
    "            }\n"
    "            incr counter\n"
    "          }\n"
    "        }\n"
    "      }\n"
    "    }\n"
    "    {focusin} {\n"
    "      if {$tkSteal_priv($pathName,initialized)} {\n"
    "        tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "          -windowid windowid\n"
    "        catch \"xaccess eventfocusin \\\n"
    "          -windowid $windowid\"\n"
    "      }\n"
    "    }\n"
    "    {focusout} {\n"
    "      if {$tkSteal_priv($pathName,initialized)} {\n"
    "        tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "          -windowid windowid\n"
    "        catch \"xaccess eventfocusout \\\n"
    "          -windowid $windowid\"\n"
    "      }\n"
    "    }\n"
    "    {redi*} {\n"
    "      if {$tkSteal_priv($pathName,initialized)} {\n"
    "        tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "          -windowid windowid\n"
    "\n"
    "        catch \"xaccess eventconfigure \\\n"
    "          -windowid $windowid \\\n"
    "          -borderwidth 0 \\\n"
    "          -x [winfo rootx ${pathName}.cbl] \\\n"
    "          -y [winfo rooty ${pathName}.cbl] \\\n"
    "          -width [winfo width $pathName.cbl] \\\n"
    "          -height [winfo height $pathName.cbl]\"\n"
    "      }\n"
    "    }\n"
    "    {buttonclick} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName buttonclick button ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventbuttonpress -windowid $windowid -button [lindex $args 0]\"\n"
    "        catch \"xaccess eventbuttonrelease -windowid $windowid -button [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventbuttonpress -windowid $windowid -button [lindex $args 0] -state [lindex $args 1]\"\n"
    "        catch \"xaccess eventbuttonrelease -windowid $windowid -button [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {buttonpress} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName buttonpress button ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventbuttonpress -windowid $windowid -button [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventbuttonpress -windowid $windowid -button [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {buttonrelease} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName buttonpress button ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventbuttonrelease -windowid $windowid -button [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventbuttonrelease -windowid $windowid -button [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {keyclick} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName keytype keycode ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventkeypress -windowid $windowid -keycode [lindex $args 0]\"\n"
    "        catch \"xaccess eventkeyrelease -windowid $windowid -keycode [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventkeypress -windowid $windowid -keycode [lindex $args 0] -state [lindex $args 1]\"\n"
    "        catch \"xaccess eventkeyrelease -windowid $windowid -keycode [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {keypress} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName keypress keycode ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventkeypress -windowid $windowid -keycode [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventkeypress -windowid $windowid -keycode [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {keyrelease} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName keyrelease keycode ?state?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess eventkeyrelease -windowid $windowid -keycode [lindex $args 0]\"\n"
    "      } {\n"
    "        catch \"xaccess eventkeyrelease -windowid $windowid -keycode [lindex $args 0] -state [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {sendstring} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName sendstring string ?interval?\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      if {[llength $args] == 1} {\n"
    "        catch \"xaccess sendstring -windowid $windowid -data \\{[lindex $args 0]\\}\"\n"
    "      } {\n"
    "        catch \"xaccess sendstring -windowid $windowid -data \\{[lindex $args 0]\\} -interval [lindex $args 1]\"\n"
    "      }\n"
    "    }\n"
    "    {motion} {\n"
    "      if {[llength $args] != 1 && [llength $args] != 2} {\n"
    "        error \"wrong # of args: should be \\\"$pathName motion x y\\\"\"\n"
    "      }\n"
    "      tkSteal_getarg $tkSteal_priv($pathName,config) \\\n"
    "        -windowid windowid\n"
    "      catch \"xaccess eventmotion -windowid $windowid -rootx [winfo rootx ${pathName}.cbl] -rooty [winfo rooty ${pathName}.cbl]\"  \n"
    "\n"
    "    }\n"
    "    {stoptksteal} {\n"
    "      if {[llength $args] != 0} {\n"
    "        error \"wrong # of args: should be \\\"$pathName stoptksteal\\\"\"\n"
    "      }\n"
    "      tkSteal_stop $pathName\n"
    "    }\n"
    "  }\n"
    "  return \"\"\n"
    "}\n"
    "\n"
    " proc tkSteal_redisplay {pathName} {\n"
    "  global tkSteal_priv\n"
    "\n"
    "  if {$tkSteal_priv($pathName,initialized)} {\n"
    "    $pathName redisplay\n"
    "  }\n"
    "}\n"
    "\n"
    "\n"
    ;
/* End of Tcl code */
/* Init routine to drag this code into our program...*/
int tkSteal_Init (Tcl_Interp *interp)
{
    if (Tcl_Eval(interp,initCmd) != 0) {
       printf("tcl error : %s\n",interp->result);
       return TCL_ERROR;
    }
    return TCL_OK;
}
/* End of C code */
