#!/bin/sh
export QTBASE=/usr/local/Trolltech/$EPICS_HOST_ARCH
export QTHOME=$QTBASE/Qt-4.8.2
export QTCREATORLIBS=$QTBASE/qtcreator-2.6.0/lib/qtcreator
export QTCREATORPATH=$QTBASE/qtcreator-2.6.0/bin
export BINQT=$QTBASE/binQt
export PATH=.:$BINQT:$QTHOME/bin:$QTCREATORPATH:$PATH

if ! kdialog --warningcontinuecancel 'Moechten Sie ein save ausdruecken?'; then
exit;
fi

#cd /tmp

declare -a arr=(60kev.prc dom.prc 860kvbend.prc 860kvquad.prc 860kvkol.prc inj2mag.prc inj2hf.prc)
count=0
blanc=" "

for i in ${arr[@]}
do
   echo $i 
   kdialog --title "caQtDM Pop-Up" --passivepopup $i 2 &
   caQtDM_Hipa -print $i
   myfile='caQtDM_'$count'.ps'
   cp caQtDM.ps $myfile
   let count=count+1
   allfiles=$allfiles$blanc$myfile
   echo $allfiles
done

gs -sDEVICE=pswrite -sOutputFile=caQtDM_out.ps -dNOPAUSE -dBATCH -sPAPERSIZE=a4  $allfiles >/dev/null 2>&1 
psnup -2 -c -d -m10 -pA4  caQtDM_out.ps | /home/ACS/Control/Bin/duplex.pl | lp -c
rm *.ps

